Cert Testing Helper Library +  Dynamic Cert Creation
world-federation-of-advertisers/common-jvm pull request #15
Opened 2021-07-22 17:37 UTC by stevenwarejones

2021-07-22 20:00 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEfNCXDclsM0Vno96m:-MfEfNCXDclsM0Vno96n:bxyh16n) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/BUILD.bazel#L12)):*
> ```Starlark
>     srcs = glob(["*.kt"]),
>     data = [
>         "//src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata:aggregator_server.key",
> ```

Put these in logical filegroups and have separate `TestData.kt` files/targets for each group (with a single target just to define TESTDATA_DIR). This way tests that only depend on static certs don't need to trigger dynamic cert generation, etc.

The actual groups should be based on which ones end up used together.

Additionally since this is in common, the files defined here should be generic and not refer to specific entities in the CMMS. Dynamic certs for those specific purposes can be defined in more localized locations in their respective repos.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEm7TGBNFxmMz9__yu:-MfEm7TGBNFxmMz9__yv:bk0j5gb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L1)):*
> ```Starlark
> # Copyright 2020 The Cross-Media Measurement Authors
> ```

These macros should probably be defined under //build so that other packages can define their own dynamic certs. This means that openssl.cnf should be put there too, declared in the BUILD.bazel file using `exports_files`. It should be referenced directly by label (i.e. `@wfa_common_jvm//build/<path>:openssl.cnf`) and specified in srcs (e.g. `srcs = srcs + [<label>]`).
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEiICl9EPXXDnlNJ5a:-MfEiICl9EPXXDnlNJ5b:b-g8ku3p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L19)):*
> ```Starlark
> """
> 
> def generate_root_certificate(name, srcs, visibility = None):
> ```

Document this. e.g. describe that it generates a root/CA certificate and private key using OpenSSL using elliptic curve crypto over the P-256 curve.

See https://github.com/bazelbuild/stardoc/blob/master/docs/writing_stardoc.md#macro-documentation
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEgJKK87-5u4y-B2gi:-MfEgJKK87-5u4y-B2gj:bwxjpy1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L27)):*
> ```
> $(@D)
> ```
Not sure you need this. I think it outputs to this location by default. If you do need it, I'd recommend using `$(RULEDIR)` instead as it has clearer semantics.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEixkODkFHHXc1NYIT:-MfEixkODkFHHXc1NYIU:b-2o3f81) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L27)):*
> ```Starlark
>             name + ".key",
>         ],
>         cmd = ("openssl req -out $(@D)/%s.pem" % (name) +
> ```

nit: might be clearer to assemble the args as an array and use `join`
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEi9b_-eFT0J5-SvS5:-MfEi9b_-eFT0J5-SvS6:bkjh9i4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L30)):*
> ```
> /O=Server CA/CN=ca.server.example.com
> ```
Take the organization and common name in as args to the macro.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEj_7j8U8HsVJFmvV3:-MfEj_7j8U8HsVJFmvV4:b-kwi61q) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L35)):*
> ```Starlark
>     )
> 
> def generate_server_certificate(name, root, srcs, visibility = None):
> ```

Document macro to explain what it does.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEj5kk5yomRnVYOOvT:-MfEj5kk5yomRnVYOOvU:b-2eo8jy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L40)):*
> ```
> name + ".csr",
> ```
This is a temporary intermediate file that we don't need in the declared output. Delete it in cmd if Bazel complains about it being undeclared.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEjJz70QHpM5BTg00b:-MfEjJz70QHpM5BTg00c:b-61hrhf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L48)):*
> ```
> ;
> ```
Use `&&` rather than `;` so the whole command fails if the first part fails.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEjfkeCAFbbaEyBYtk:-MfEjfkeCAFbbaEyBYtl:bfqjxyd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L54)):*
> ```
> ["//visibility:public"]
> ```
Use visibility arg


<!-- Sent from Reviewable.io -->

2021-07-23 01:36 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEfNCXDclsM0Vno96m:-MfF8jN3Aq9tvJepL5_2:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/BUILD.bazel#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put these in logical filegroups and have separate `TestData.kt` files/targets for each group (with a single target just to define TESTDATA_DIR). This way tests that only depend on static certs don't need to trigger dynamic cert generation, etc.

The actual groups should be based on which ones end up used together.

Additionally since this is in common, the files defined here should be generic and not refer to specific entities in the CMMS. Dynamic certs for those specific purposes can be defined in more localized locations in their respective repos.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEm7TGBNFxmMz9__yu:-MfFAR139Voc2EGf8jZm:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These macros should probably be defined under //build so that other packages can define their own dynamic certs. This means that openssl.cnf should be put there too, declared in the BUILD.bazel file using `exports_files`. It should be referenced directly by label (i.e. `@wfa_common_jvm//build/<path>:openssl.cnf`) and specified in srcs (e.g. `srcs = srcs + [<label>]`).
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEiICl9EPXXDnlNJ5a:-MfEzpCu9V6bt02GS9-9:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document this. e.g. describe that it generates a root/CA certificate and private key using OpenSSL using elliptic curve crypto over the P-256 curve.

See https://github.com/bazelbuild/stardoc/blob/master/docs/writing_stardoc.md#macro-documentation
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEixkODkFHHXc1NYIT:-MfFyxFy2Z1fzw-iCiNa:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: might be clearer to assemble the args as an array and use `join`
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEgJKK87-5u4y-B2gi:-MfG-JmHBBYo-L-eZlsa:b-kk20pd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> $(@D)
> ```
Not sure you need this. I think it outputs to this location by default. If you do need it, I'd recommend using `$(RULEDIR)` instead as it has clearer semantics.
</blockquote></details>

it is needed but changed it to `RULEDIR`
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEi9b_-eFT0J5-SvS5:-MfF-fmS7TQl-Mk8DARw:b-v8gx23) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> /O=Server CA/CN=ca.server.example.com
> ```
Take the organization and common name in as args to the macro.
</blockquote></details>

done. i left these as default values.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEj_7j8U8HsVJFmvV3:-MfF0CJN2BQiaX5OhyO4:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document macro to explain what it does.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEj5kk5yomRnVYOOvT:-MfFz2rTCKtrgkoMXnO_:b-wzaf3i) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> name + ".csr",
> ```
This is a temporary intermediate file that we don't need in the declared output. Delete it in cmd if Bazel complains about it being undeclared.
</blockquote></details>

it didn't complain :)
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEjJz70QHpM5BTg00b:-MfF0NoN6rJGdLmv20im:bhizrkh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ;
> ```
Use `&&` rather than `;` so the whole command fails if the first part fails.
</blockquote></details>

done. good catch
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfEjfkeCAFbbaEyBYtk:-MfF0PVCEAJPUA3LqSZ0:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6cffad3bc7768dab34326f9e87868b3a975fb3fb/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/macros.bzl#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ["//visibility:public"]
> ```
Use visibility arg
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-23 18:30 UTC, SanjayVas requested changes
> Reviewed 1 of 6 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 8 unresolved discussions (waiting on @stevenwarejones)

___
*[build/wfa/macros.bzl, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJOr-vB5ISYuhKPCn3:-MfJOr-vB5ISYuhKPCn4:b96qw4x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L21)):*
> ```
> srcs = [],
> ```
This doesn't need any other sources.
___
*[build/wfa/macros.bzl, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJOHXs1e4g8Fno-Bn2:-MfJOHXs1e4g8Fno-Bn3:b-r7wf6t) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L24)):*
> ```
> ["//visibility:public"]
> ```
Just leave this as None to follow the inherent defaults. Otherwise this will override the package-level default visibility if the arg isn't specified.
___
*[build/wfa/macros.bzl, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJOwtI7yjDPMcOkinm:-MfJOwtI7yjDPMcOkinn:ba8fnp9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L53)):*
> ```
> "@wfa_common_jvm//build/wfa:openssl.cnf"
> ```
Either use ssl_conf here or drop the arg and keep it hard-coded.
___
*[build/wfa/macros.bzl, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJP4aRCKs6eS3AmxZG:-MfJP4aRCKs6eS3AmxZH:b-e8zdc6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L70)):*
> ```
> Generates a certificate signing request, private key, and a certificate chain.
> ```
The CSR isn't one of the outputs and therefore need not be mentioned. Simply saying this generates a new private key and certificate that's signed by the specified CA.
___
*[build/wfa/macros.bzl, line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJPVL80fTq8dUaUo6V:-MfJPVL80fTq8dUaUo6W:ban34qr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L108)):*
> ```Starlark
>     native.genrule(
>         name = name,
>         srcs = srcs + [ssl_conf],
> ```

Also specify the root key and cert files as srcs. This means that those files should actually be separate arguments to the macro.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/CertificateTesting.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJQKEe6QC2VCGnov4a:-MfJQKEe6QC2VCGnov4b:bbahh54) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/CertificateTesting.kt#L40)):*
>  generated dynamically each test.

This isn't actually true. Bazel will happily reuse a genrule output from cache if it hasn't been invalidated, so this isn't guaranteed to be generated on each test.

Static in this case means tracked by version control, and dynamic means generated as-needed by the build system.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel, line 10 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_Yeh6ejPD2ow2Rcd:-MfJ_Yeh6ejPD2ow2Rce:b1sjhzb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel#L10)):*
> ```Starlark
> )
> 
> generate_root_certificate(
> ```

Why do we actually need any of these additional certs here in common? I don't see any tests in this repo that would use them.

Maybe we just need the macros in common-jvm and for other repos/packages to define additional targets as-needed.
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_1zt8hlKQ4aLWeTL:-MfJ_1zt8hlKQ4aLWeTM:b-4lu8gy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L66)):*
> ```Kotlin
> 
>   @Test
>   fun `readCertificate reads dynamically created cert from PEM file`() {
> ```

This test seems unnecessary, as the part of the SUT being tested isn't different for static certs vs. those generated by the build system. There's in fact no way to determine the difference from the SUT's POV.

We haven't really done any specific testing of macros and have sort of assumed they'd work, as they get inherently covered by the tests that use them.


<!-- Sent from Reviewable.io -->

2021-07-23 19:27 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones)

___
*[build/wfa/macros.bzl, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJp3iB1O10qHMKcXvk:-MfJp3iB1O10qHMKcXvl:b-g7ofls) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L62)):*
> ```
> server
> ```
I got a question about the name.

In the case of mTLS, isn't the client certs generated in the same way?

should this just be called `generate_and _sign_certificate`?


<!-- Sent from Reviewable.io -->

2021-07-23 19:37 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[build/wfa/macros.bzl, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJp3iB1O10qHMKcXvk:-MfJr6by8GnTChdW_Tdi:b-sqjkvy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L62)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> server
> ```
I got a question about the name.

In the case of mTLS, isn't the client certs generated in the same way?

should this just be called `generate_and _sign_certificate`?
</blockquote></details>

Yeah, you're right that this isn't necessarily a cert that's used in the server role for TLS. e.g. a binary would most likely use the same TLS cert for receiving RPCs as it would for being a client for another server using mTLS. Maybe `generate_user_certificate`, as that's what the default OpenSSL config calls that type of cert?


<!-- Sent from Reviewable.io -->

2021-07-23 19:57 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[build/wfa/macros.bzl, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJp3iB1O10qHMKcXvk:-MfJwQqi4N1bzvUX27WD:bwk2ggx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, you're right that this isn't necessarily a cert that's used in the server role for TLS. e.g. a binary would most likely use the same TLS cert for receiving RPCs as it would for being a client for another server using mTLS. Maybe `generate_user_certificate`, as that's what the default OpenSSL config calls that type of cert?
</blockquote></details>

+1 for generate_user_certificate


<!-- Sent from Reviewable.io -->

2021-07-23 21:07 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[build/wfa/macros.bzl, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJOr-vB5ISYuhKPCn3:-MfJr55CAqwS9ySy7cb7:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> srcs = [],
> ```
This doesn't need any other sources.
</blockquote></details>

done
___
*[build/wfa/macros.bzl, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJOHXs1e4g8Fno-Bn2:-MfJrAc62NYbxAzlog8x:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ["//visibility:public"]
> ```
Just leave this as None to follow the inherent defaults. Otherwise this will override the package-level default visibility if the arg isn't specified.
</blockquote></details>

done
___
*[build/wfa/macros.bzl, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJOwtI7yjDPMcOkinm:-MfJrIVl48Og_AEQRoLI:bopcqmb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "@wfa_common_jvm//build/wfa:openssl.cnf"
> ```
Either use ssl_conf here or drop the arg and keep it hard-coded.
</blockquote></details>

oops. missed that when cleaning things up. thx.
___
*[build/wfa/macros.bzl, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJp3iB1O10qHMKcXvk:-MfK17KQ7Ha7agcLmRQ9:b10azgx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L62)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

+1 for generate_user_certificate
</blockquote></details>

changed this to generate_user_certificate .... I think its implied it can be used for asymmetric crypto-type activities.
___
*[build/wfa/macros.bzl, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJP4aRCKs6eS3AmxZG:-MfK1VKf8vqogDY-bGVL:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Generates a certificate signing request, private key, and a certificate chain.
> ```
The CSR isn't one of the outputs and therefore need not be mentioned. Simply saying this generates a new private key and certificate that's signed by the specified CA.
</blockquote></details>

done
___
*[build/wfa/macros.bzl, line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJPVL80fTq8dUaUo6V:-MfKAw0uE_thQQe0479c:bx8zidn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/build/wfa/macros.bzl#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also specify the root key and cert files as srcs. This means that those files should actually be separate arguments to the macro.
</blockquote></details>

i split these out into separate sources. Looks like this now
```
generate_user_certificate(
    name = "dynamic_1",
    root_certificate = ":dynamic_1_root.pem",
    root_key = ":dynamic_1_root.key",
)
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/CertificateTesting.kt, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJQKEe6QC2VCGnov4a:-MfK2rA62dq5rznx4igC:bp2276v) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/CertificateTesting.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

>  generated dynamically each test.

This isn't actually true. Bazel will happily reuse a genrule output from cache if it hasn't been invalidated, so this isn't guaranteed to be generated on each test.

Static in this case means tracked by version control, and dynamic means generated as-needed by the build system.

</blockquote></details>

good point. updated the comment
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel, line 10 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_Yeh6ejPD2ow2Rcd:-MfK33BTAaOT9IcKAqt6:b-rtp13d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do we actually need any of these additional certs here in common? I don't see any tests in this repo that would use them.

Maybe we just need the macros in common-jvm and for other repos/packages to define additional targets as-needed.
</blockquote></details>

I just wanted a test within the repo of generating one dynamically and testing it to make sure it works.
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_1zt8hlKQ4aLWeTL:-MfK39ZC7HGCZzFqPkYE:brh5548) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This test seems unnecessary, as the part of the SUT being tested isn't different for static certs vs. those generated by the build system. There's in fact no way to determine the difference from the SUT's POV.

We haven't really done any specific testing of macros and have sort of assumed they'd work, as they get inherently covered by the tests that use them.
</blockquote></details>

ditto above. I wanted a way to test that the dynamic certificate was created correctly and give an example consuming it. I'd prefer to keep it all else being equal.


<!-- Sent from Reviewable.io -->

2021-07-23 21:22 UTC, wangyaopw approved these changes

2021-07-23 22:27 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/macros.bzl, line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfKNxMoCW3iMUj4lV4e:-MfKNxMoCW3iMUj4lV4f:babx56r) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ad2d631ccb05ac592756de2793bd763adfae2b7c/build/wfa/macros.bzl#L74)):*
> ```
> ca
> ```
super nit: capital `CA` since it's an initialism for Certificate Authority
___
*[build/wfa/macros.bzl, line 98 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfKPfWB3rLE5JS2TIml:-MfKPfWB3rLE5JS2TImm:bs7rjk7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ad2d631ccb05ac592756de2793bd763adfae2b7c/build/wfa/macros.bzl#L98)):*
> ```Starlark
>         "-days 365",
>         "-req",
>         "-CA $(RULEDIR)/{}".format(root_certificate.split(":")[1]),
> ```

You'll want to use `$(location {})` in the template string and put in the value of `root_certificate` like you do for `ssl_conf`. This is because `root_certificate` is a label.

Do the same for `root_key`
___
*[build/wfa/macros.bzl, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfKQ2VFCEVEHG4tPo0f:-MfKQ2VFCEVEHG4tPo0g:b9a94tj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ad2d631ccb05ac592756de2793bd763adfae2b7c/build/wfa/macros.bzl#L106)):*
> ```
> [root_key] + [root_certificate] + [ssl_conf]
> ```
[root_key, root_certificate, ssl_conf]
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel, line 10 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_Yeh6ejPD2ow2Rcd:-MfKR_CpA1_jkmCoi5m4:b7dh5e1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel#L10)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I just wanted a test within the repo of generating one dynamically and testing it to make sure it works.
</blockquote></details>

See below comment re: testing the macro itself. If you're just testing the macro, you don't need these files referenced in Kotlin and can just have your test certs define in the //build tree next to the macro validator test.
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_1zt8hlKQ4aLWeTL:-MfKQkWq8kqWZqKJiZXp:bqn741l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto above. I wanted a way to test that the dynamic certificate was created correctly and give an example consuming it. I'd prefer to keep it all else being equal.
</blockquote></details>

If you really want this, it should be a separate test specifically for the macro. Usually you'd use a minimal `sh_test` for such a thing. See https://docs.bazel.build/versions/main/skylark/testing.html#for-validating-artifacts.

For example, you could use the OpenSSL `verify` subcommand to verify the chain of the user cert, which would inherently verify that the CA cert is also valid. This can optionally verify things like the subject common name using `-verify_hostname` This could just go in the same package under build and need not be in a test tree. If you'd like, you can file a GitHub issue for me to write a validator test for the macro in a follow-up PR if you don't want to block this PR for it.

Regardless, I don't think this test belongs here as it's not testing the SUT. I'd rather not have it regardless of whether we have a separate test for the macro. 


<!-- Sent from Reviewable.io -->

2021-07-26 14:49 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_1zt8hlKQ4aLWeTL:-MfYHgme2arczIkVJf67:byik327) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you really want this, it should be a separate test specifically for the macro. Usually you'd use a minimal `sh_test` for such a thing. See https://docs.bazel.build/versions/main/skylark/testing.html#for-validating-artifacts.

For example, you could use the OpenSSL `verify` subcommand to verify the chain of the user cert, which would inherently verify that the CA cert is also valid. This can optionally verify things like the subject common name using `-verify_hostname` This could just go in the same package under build and need not be in a test tree. If you'd like, you can file a GitHub issue for me to write a validator test for the macro in a follow-up PR if you don't want to block this PR for it.

Regardless, I don't think this test belongs here as it's not testing the SUT. I'd rather not have it regardless of whether we have a separate test for the macro. 
</blockquote></details>

added some tests. lmk if they cover the basics of what you wanted.
___
*[build/wfa/macros.bzl, line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfKNxMoCW3iMUj4lV4e:-MfXiZNe846bEFDBypSs:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ad2d631ccb05ac592756de2793bd763adfae2b7c/build/wfa/macros.bzl#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ca
> ```
super nit: capital `CA` since it's an initialism for Certificate Authority
</blockquote></details>

done
___
*[build/wfa/macros.bzl, line 98 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfKPfWB3rLE5JS2TIml:-MfXjCcY9_yUR6ZjArHF:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ad2d631ccb05ac592756de2793bd763adfae2b7c/build/wfa/macros.bzl#L98)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll want to use `$(location {})` in the template string and put in the value of `root_certificate` like you do for `ssl_conf`. This is because `root_certificate` is a label.

Do the same for `root_key`
</blockquote></details>

done
___
*[build/wfa/macros.bzl, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfKQ2VFCEVEHG4tPo0f:-MfXjFJ28YXL3lIuGUUz:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ad2d631ccb05ac592756de2793bd763adfae2b7c/build/wfa/macros.bzl#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> [root_key] + [root_certificate] + [ssl_conf]
> ```
[root_key, root_certificate, ssl_conf]
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-26 14:50 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel, line 10 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_Yeh6ejPD2ow2Rcd:-MfYHq0t7lLNVZMYeIHJ:byik327) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See below comment re: testing the macro itself. If you're just testing the macro, you don't need these files referenced in Kotlin and can just have your test certs define in the //build tree next to the macro validator test.
</blockquote></details>

added some tests. lmk if they cover the basics of what you wanted.
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_1zt8hlKQ4aLWeTL:-MfYHqoV2Fev0WM7-cLM:b-ipqon6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

added some tests. lmk if they cover the basics of what you wanted.
</blockquote></details>

removed the kt tests


<!-- Sent from Reviewable.io -->

2021-07-26 19:12 UTC, SanjayVas requested changes
> Reviewed 4 of 8 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 10 of 11 files reviewed, 13 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/BUILD.bazel, line 23 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZA3vB3BQmjirGBPdc:-MfZA3vB3BQmjirGBPdd:b-kl2ysd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/BUILD.bazel#L23)):*
> ```Starlark
>     srcs = [":generate_root_certificate_validator.sh"],
>     args = [
>         "$(location :test_root.key)",
> ```

You don't need to pass these as args. You can read data from runfiles in Bash similar to how we do in Java/Kotlin. See https://github.com/bazelbuild/bazel/blob/b4cc44c978bc0e25b6652b66018b6aad12bff820/tools/bash/runfiles/runfiles.bash
___
*[build/wfa/generate_root_certificate_validator.sh, line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8xAn3C_5FKsbfzID:-MfZ8xAn3C_5FKsbfzIE:bpyw5y0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L1)):*
> ```Shell
> # Copyright 2021 The Cross-Media Measurement Authors
> ```

I don't know if we're formally adopted a shell style guide, but https://google.github.io/styleguide/shellguide.html has some pretty good recommendations. It's the source of my style comments below.
___
*[build/wfa/generate_root_certificate_validator.sh, line 14 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8Zg34fpMVJgkJTSB:-MfZ8Zg34fpMVJgkJTSC:b-i5kzrf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L14)):*
> ```Shell
> # See the License for the specific language governing permissions and
> # limitations under the License.
> ```

Add shebang to indicate that this should be run using bash.

```
#!/usr/bin/env bash
```
___
*[build/wfa/generate_root_certificate_validator.sh, line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ82fVCnWtGSZsDuG0:-MfZ82fVCnWtGSZsDuG1:bfhumxl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L15)):*
> ```
> set -ex
> ```
I'd recommend `set -e -o pipefail` to match the genrule shell flags. We don't really need `-x`, as I think that there's a Bazel debug flag that'll apply it if really needed.
___
*[build/wfa/generate_root_certificate_validator.sh, line 18 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8mNP-hvD9BlZ_AbU:-MfZ8mNP-hvD9BlZ_AbV:b-8xn2of) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L18)):*
> ```Shell
> 
> # Check that private key is proper EC key
> ec_key_check=$(openssl ec -check -noout -in $1 2>&1)
> ```

Always quote strings containing command substitutions.
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-MfZCeEZ4Xg2DEOtxQeN:b37jvs9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
> ```Shell
> # Check that private key is proper EC key
> ec_key_check=$(openssl ec -check -noout -in $1 2>&1)
> if [ "$ec_key_check" != $'read EC key\nEC Key valid.' ]; then
> ```

Prefer checking exit codes rather than looking at output when possible.

Assuming that `-check` to `openssl ec` makes it return a non-zero exit code if it's not a valid EC key, then you should be able to do something like

```
if ! [[ openssl ec -check -noout -in "${key_file}" ]]; then
   echo 'message' >&2
   exit 1
fi
```

This way you don't need to capture output. If the error output of the command is sufficient and you don't need your own message, you can simply put the command without a conditional and `set -e` will cause the test to exit with a non-zero code on its own.
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCiIaDh-7jDBtgmzr:-MfZCiIaDh-7jDBtgmzs:bxir0oa) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
> ```
> if [
> ```
Use `[[` for tests rather than `[`.
___
*[build/wfa/generate_root_certificate_validator.sh, line 20 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ94cpDj1PJltjU6DX:-MfZ94cpDj1PJltjU6DY:bx9f6yq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L20)):*
> ```Shell
> ec_key_check=$(openssl ec -check -noout -in $1 2>&1)
> if [ "$ec_key_check" != $'read EC key\nEC Key valid.' ]; then
>   echo "Invalid EC Key:"
> ```

Output all messages to stderr.
___
*[build/wfa/generate_root_certificate_validator.sh, line 21 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ9Kd0Bf5cL-yej_Y3:-MfZ9Kd0Bf5cL-yej_Y4:b-xsnn1a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L21)):*
> ```Shell
> if [ "$ec_key_check" != $'read EC key\nEC Key valid.' ]; then
>   echo "Invalid EC Key:"
>   echo $ec_key_check
> ```

Always quote strings containing variables, and prefer "${var_name}" syntax
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel, line 10 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfJ_Yeh6ejPD2ow2Rcd:-MfZDaiL6cnAMDtDqYVE:b3b41k8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1854779043b0b12a0f43e78940778877fb73a3db/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/BUILD.bazel#L10)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

added some tests. lmk if they cover the basics of what you wanted.
</blockquote></details>

They do, thanks! Just had some style comments related to Bash specifically.
___
*[build/wfa/generate_certificate_macros.bzl, line 98 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ7EKI8ItHblcO680U:-MfZ7EKI8ItHblcO680V:bf00l4g) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_certificate_macros.bzl#L98)):*
> ```
> root_certificate.split(":")[1]
> ```
Drop the split. Just `root_certificate`. `location` can work on any arbitrary label.
___
*[build/wfa/generate_certificate_macros.bzl, line 99 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ7LL2Bhkzb0A0jeNq:-MfZ7LL2Bhkzb0A0jeNr:btjlj6d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_certificate_macros.bzl#L99)):*
> ```
> root_key.split(":")[1]
> ```
Same here


<!-- Sent from Reviewable.io -->

2021-07-26 20:01 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 10 of 11 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[build/wfa/BUILD.bazel, line 23 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZA3vB3BQmjirGBPdc:-MfZLQTtB7IT_q5CI74o:b-xsko21) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/BUILD.bazel#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need to pass these as args. You can read data from runfiles in Bash similar to how we do in Java/Kotlin. See https://github.com/bazelbuild/bazel/blob/b4cc44c978bc0e25b6652b66018b6aad12bff820/tools/bash/runfiles/runfiles.bash
</blockquote></details>

This way the shell script doesn't need to know the file names of the root and user keys. I prefer it this way. Okay to leave as is?
___
*[build/wfa/generate_root_certificate_validator.sh, line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8xAn3C_5FKsbfzID:-MfZOQl55NCNfRboNEqr:b-fo4iry) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't know if we're formally adopted a shell style guide, but https://google.github.io/styleguide/shellguide.html has some pretty good recommendations. It's the source of my style comments below.
</blockquote></details>

read through some of the guide and tried to adopt a few things
___
*[build/wfa/generate_root_certificate_validator.sh, line 14 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8Zg34fpMVJgkJTSB:-MfZIHKu8DOcwwpYBhHv:bd30ifx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add shebang to indicate that this should be run using bash.

```
#!/usr/bin/env bash
```
</blockquote></details>

good catch
___
*[build/wfa/generate_root_certificate_validator.sh, line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ82fVCnWtGSZsDuG0:-MfZI4EDCUay8xk1FyHD:bydm65a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> set -ex
> ```
I'd recommend `set -e -o pipefail` to match the genrule shell flags. We don't really need `-x`, as I think that there's a Bazel debug flag that'll apply it if really needed.
</blockquote></details>

I was reading that's not really recommended ```this setting prevents errors in a pipeline from being masked. If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline. By default, the pipeline's return code is that of the last command even if it succeeds. Imagine finding a sorted list of matching lines in a file:```
___
*[build/wfa/generate_root_certificate_validator.sh, line 18 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8mNP-hvD9BlZ_AbU:-MfZI1OyEGagntm0wXpQ:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Always quote strings containing command substitutions.
</blockquote></details>

done
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCiIaDh-7jDBtgmzr:-MfZHuPR1y4pImBaQURt:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> if [
> ```
Use `[[` for tests rather than `[`.
</blockquote></details>

done
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-MfZJiz53gHd-bQ0nxcR:b-l29uyf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Prefer checking exit codes rather than looking at output when possible.

Assuming that `-check` to `openssl ec` makes it return a non-zero exit code if it's not a valid EC key, then you should be able to do something like

```
if ! [[ openssl ec -check -noout -in "${key_file}" ]]; then
   echo 'message' >&2
   exit 1
fi
```

This way you don't need to capture output. If the error output of the command is sufficient and you don't need your own message, you can simply put the command without a conditional and `set -e` will cause the test to exit with a non-zero code on its own.
</blockquote></details>

changed some of the checks to just check for error codes. Still checking manually for O/CN and that the public keys match. For the O/CN verify, when I run `openssl verify -CAfile bazel-out/k8-fastbuild/bin/build/wfa/test_root.pem -verify_hostname some-user.com bazel-out/k8-fastbuild/bin/build/wfa/test_user.pem`, I'm getting the following error message:
```O = Some User Org, CN = some-user.com
error 62 at 0 depth lookup: Hostname mismatch```
```

___
*[build/wfa/generate_root_certificate_validator.sh, line 20 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ94cpDj1PJltjU6DX:-MfZHjeQ7A5p4Qk6gjSo:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Output all messages to stderr.
</blockquote></details>

done
___
*[build/wfa/generate_root_certificate_validator.sh, line 21 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ9Kd0Bf5cL-yej_Y3:-MfZHvtQ33cgmiDqe7e7:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Always quote strings containing variables, and prefer "${var_name}" syntax
</blockquote></details>

done
___
*[build/wfa/generate_certificate_macros.bzl, line 98 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ7EKI8ItHblcO680U:-MfZGHORD_wSLyUr1j4V:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_certificate_macros.bzl#L98)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> root_certificate.split(":")[1]
> ```
Drop the split. Just `root_certificate`. `location` can work on any arbitrary label.
</blockquote></details>

done
___
*[build/wfa/generate_certificate_macros.bzl, line 99 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ7LL2Bhkzb0A0jeNq:-MfZI9_n5LKyGXVwJagm:bb7f2mf) ([raw file](https://github.c [...]

2021-07-26 21:37 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[build/wfa/BUILD.bazel, line 23 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZA3vB3BQmjirGBPdc:-MfZ_1qh5MffnnOGjNnj:b-bdiutp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/BUILD.bazel#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This way the shell script doesn't need to know the file names of the root and user keys. I prefer it this way. Okay to leave as is?
</blockquote></details>

It's not much different than how our Kotlin tests read known test data files, but I left this on "Discussing" disposition to indicate that it's optional.
___
*[build/wfa/generate_root_certificate_validator.sh, line 14 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8Zg34fpMVJgkJTSB:-MfZjipE60IaP_b06LcU:bl1msae) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L14)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

good catch
</blockquote></details>

Generally prefer the shebang I mentioned as it's more cross-platform compatible, though not a big deal since we only expect to run this on GNU Linux.
___
*[build/wfa/generate_root_certificate_validator.sh, line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ82fVCnWtGSZsDuG0:-MfZ_cSS9pnlr5fKW5HT:b-caiqxj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was reading that's not really recommended ```this setting prevents errors in a pipeline from being masked. If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline. By default, the pipeline's return code is that of the last command even if it succeeds. Imagine finding a sorted list of matching lines in a file:```
</blockquote></details>

This test doesn't have any pipelines so it's somewhat moot. Was just commenting that it's what Bazel applies when executing a genrule.

As an aside, I don't see how the bit you quoted is a negative recommendation. It specifically says setting this *prevents* the masking of errors and ensures that the error gets propagated.
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-MfZe3PX8WyY6KrxHHH6:b-g4f5rj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

changed some of the checks to just check for error codes. Still checking manually for O/CN and that the public keys match. For the O/CN verify, when I run `openssl verify -CAfile bazel-out/k8-fastbuild/bin/build/wfa/test_root.pem -verify_hostname some-user.com bazel-out/k8-fastbuild/bin/build/wfa/test_user.pem`, I'm getting the following error message:
```O = Some User Org, CN = some-user.com
error 62 at 0 depth lookup: Hostname mismatch```
</blockquote></details>

Huh, weird. I don't know how `-verify_hostname` is supposed to work then. I suppose that's fine, since you'd need to check output to verify other parts of the subject anyway.
___
*[build/wfa/generate_root_certificate_validator.sh, line 20 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ94cpDj1PJltjU6DX:-MfZf6b86ASrNLO5GbfC:b-o5czho) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done
</blockquote></details>

I believe you defined the `err` function in the other script but didn't duplicate it here.
___
*[build/wfa/generate_root_certificate_validator.sh, line 20 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZg6Q1BlZejuWuLdUz:-MfZg6Q1BlZejuWuLdV-:blh17w) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L20)):*
> ```
> ${1}
> ```
I'd recommend pulling these args into variables up front for improved readability.

e.g.

```
readonly key_file="$1"
readonly certificate_pem_file="$2"
```

The `${varname}` syntax is also usually not used for positional arg vars. (Just use `$1`, etc.). See google.github.io/styleguide/shellguide.html#quoting
___
*[build/wfa/generate_root_certificate_validator.sh, line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZeQwJEGLvCVyta-Ti:-MfZeQwJEGLvCVyta-Tj:b-bx7ean) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L21)):*
> ```Shell
> # Check that private key is proper EC key
> openssl ec -check -noout -in "${1}"
> if [[ $? -ne 0 ]]; then
> ```

I believe due to the fact that you have `set -e`, this line will never be hit. The script will have already exited if the command failed.

If you really want to check for a non-zero error code from a command so you can output a custom message, you'd do so by wrapping the command like `if ! [[ command ]]; then`, which will also cause the command *not* to immediately exit due to `set -e`.
___
*[build/wfa/generate_root_certificate_validator.sh, line 28 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZjH2P559EpYdPBtxZ:-MfZjH2P559EpYdPBtx_:b6dnab) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L28)):*
> ```Shell
> # Check that public keys match
> if [[ "$(openssl pkey -pubout -in "${1}" 2>&1)" != "$(openssl x509 -noout -pubkey -in "${2}" 2>&1)" ]]; then
>   err "Public keys do not match"
> ```

nit: Prefer single quotes when you don't need any substitution.
___
*[build/wfa/generate_user_certificate_validator.sh, line 19 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZfOHDEQkkkT_hbD9U:-MfZfOHDEQkkkT_hbD9V:b-gakwwv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_user_certificate_validator.sh#L19)):*
> ```Shell
> set -e -o pipefail
> 
> err() {
> ```

If you're going to define any functions, then the common convention is to have a `main` function and call `main "$@"` at the end of the script.


<!-- Sent from Reviewable.io -->

2021-07-27 14:25 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/generate_root_certificate_validator.sh, line 14 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ8Zg34fpMVJgkJTSB:-Mf_WMxI-M1idaAkGXQZ:b-7rl0kd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Generally prefer the shebang I mentioned as it's more cross-platform compatible, though not a big deal since we only expect to run this on GNU Linux.
</blockquote></details>

done
___
*[build/wfa/generate_root_certificate_validator.sh, line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ82fVCnWtGSZsDuG0:-Mf__dLD4jJ0xxLuzREY:b50kwmv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This test doesn't have any pipelines so it's somewhat moot. Was just commenting that it's what Bazel applies when executing a genrule.

As an aside, I don't see how the bit you quoted is a negative recommendation. It specifically says setting this *prevents* the masking of errors and ensures that the error gets propagated.
</blockquote></details>

Okay. Reading it again, I agree.
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-MfcK-Ga-Fy9YL0ZY8S2:bxm9yst) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Huh, weird. I don't know how `-verify_hostname` is supposed to work then. I suppose that's fine, since you'd need to check output to verify other parts of the subject anyway.
</blockquote></details>

figured this out. It was the ssl_conf overriding options. I changed this to the default Ubuntu 20 ssl.conf
___
*[build/wfa/generate_root_certificate_validator.sh, line 20 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZ94cpDj1PJltjU6DX:-Mf__ouhEFPulbR0xNyy:b-y3qnc4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe you defined the `err` function in the other script but didn't duplicate it here.
</blockquote></details>

yuk. thx. done
___
*[build/wfa/generate_root_certificate_validator.sh, line 20 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZg6Q1BlZejuWuLdUz:-Mf_W8Ka6p7G-vX-nT2U:b-7rl0kd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ${1}
> ```
I'd recommend pulling these args into variables up front for improved readability.

e.g.

```
readonly key_file="$1"
readonly certificate_pem_file="$2"
```

The `${varname}` syntax is also usually not used for positional arg vars. (Just use `$1`, etc.). See google.github.io/styleguide/shellguide.html#quoting
</blockquote></details>

done
___
*[build/wfa/generate_root_certificate_validator.sh, line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZeQwJEGLvCVyta-Ti:-Mfc8iyMA7ra6BzW-165:bdj6ufy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe due to the fact that you have `set -e`, this line will never be hit. The script will have already exited if the command failed.

If you really want to check for a non-zero error code from a command so you can output a custom message, you'd do so by wrapping the command like `if ! [[ command ]]; then`, which will also cause the command *not* to immediately exit due to `set -e`.
</blockquote></details>

i think it's just supposed to be `if ! command;` per https://google.github.io/styleguide/shellguide.html#environment -- changed it to that style
___
*[build/wfa/generate_root_certificate_validator.sh, line 28 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZjH2P559EpYdPBtxZ:-Mf__qavAltoIAM7wrCM:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Prefer single quotes when you don't need any substitution.
</blockquote></details>

done
___
*[build/wfa/generate_user_certificate_validator.sh, line 19 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZfOHDEQkkkT_hbD9U:-Mf_UYRc--tKG52MwcpF:b-slo0wy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_user_certificate_validator.sh#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're going to define any functions, then the common convention is to have a `main` function and call `main "$@"` at the end of the script.
</blockquote></details>

didnt know that. done.


<!-- Sent from Reviewable.io -->

2021-07-27 17:55 UTC, SanjayVas requested changes
> Reviewed 3 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-Mfd1UT_7qXhjkMIv7D7:b-ithauo) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

figured this out. It was the ssl_conf overriding options. I changed this to the default Ubuntu 20 ssl.conf
</blockquote></details>

The local openssl.cnf intentionally overrides the default config to add subject alternative name (SAN) since we'll need that for TLS. I also wasn't certain if there were license implications to including the default/example config and decided to just avoid the issue.

I get the problem though. I'm guessing `-verify_hostname` uses the SAN if it's specified rather than the subject common name. Therefore, we can't use `-verify_hostname` to verify the subject common name in all cases.
___
*[build/wfa/generate_root_certificate_validator.sh, line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZeQwJEGLvCVyta-Ti:-Mfd2viW8qikc1AKE5wN:b-g6nplm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1287c02e7ee292c1b3832ccdd61d4a75c401f9bc/build/wfa/generate_root_certificate_validator.sh#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think it's just supposed to be `if ! command;` per https://google.github.io/styleguide/shellguide.html#environment -- changed it to that style
</blockquote></details>

You're right, sorry. Thanks.
___
*[build/wfa/generate_root_certificate_validator.sh, line 32 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd3GDv5iuGk-dQM66e:-Mfd3GDv5iuGk-dQM66f:b-x3s150) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_root_certificate_validator.sh#L32)):*
> ```
> exit 1
> ```
Any reason not to move the exit into `err`?
___
*[build/wfa/generate_root_certificate_validator.sh, line 54 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd3aZiDouSrcOmffcw:-Mfd3aZiDouSrcOmffcx:b-7nsoyj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_root_certificate_validator.sh#L54)):*
> ```Shell
>   fi
> 
>   echo 'Success'
> ```

nit: This should also go to stderr. The validator should not have any output on stdout.

It's slightly confusing as stderr isn't necessarily just for errors, but rather any status messages that aren't meant to be consumed.
___
*[build/wfa/generate_root_certificate_validator.sh, line 55 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd3XKt3UnqOqPkZPqm:-Mfd3XKt3UnqOqPkZPqn:bi8gy5o) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_root_certificate_validator.sh#L55)):*
> ```
> exit 0
> ```
nit: usually you only use `exit` to exit early or with a non-default code. In this case, this is technically exiting instead of letting `main` complete.
___
*[build/wfa/generate_user_certificate_validator.sh, line 26 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd5Ett8zMua-rFyUqp:-Mfd5Etu0yvF5TGjR0c-:b-yzs3j2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_user_certificate_validator.sh#L26)):*
> ```
> readonly 
> ```
nit: If declaring in a function, you can use local variables rather than globals.

e.g.
```
local -r root_key_file="$1"
```


<!-- Sent from Reviewable.io -->

2021-07-27 18:10 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-Mfd8ID74gu5VGCyiWyu:bnwyvrm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The local openssl.cnf intentionally overrides the default config to add subject alternative name (SAN) since we'll need that for TLS. I also wasn't certain if there were license implications to including the default/example config and decided to just avoid the issue.

I get the problem though. I'm guessing `-verify_hostname` uses the SAN if it's specified rather than the subject common name. Therefore, we can't use `-verify_hostname` to verify the subject common name in all cases.
</blockquote></details>

what if I just slim down openssl.cnf to just the include? That way we can `-verify_hostname` in the test. Went ahead and did that. I like that better for now.
___
*[build/wfa/generate_root_certificate_validator.sh, line 32 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd3GDv5iuGk-dQM66e:-Mfd7cFF8EpVPCL7jg6B:b-yurupj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_root_certificate_validator.sh#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> exit 1
> ```
Any reason not to move the exit into `err`?
</blockquote></details>

was following the guideline examples on the google bash style guide.
___
*[build/wfa/generate_root_certificate_validator.sh, line 54 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd3aZiDouSrcOmffcw:-Mfd80pYAW2rpJ9K7RlC:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_root_certificate_validator.sh#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: This should also go to stderr. The validator should not have any output on stdout.

It's slightly confusing as stderr isn't necessarily just for errors, but rather any status messages that aren't meant to be consumed.
</blockquote></details>

done
___
*[build/wfa/generate_root_certificate_validator.sh, line 55 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd3XKt3UnqOqPkZPqm:-Mfd85rs7QNoZWw1nESm:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_root_certificate_validator.sh#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> exit 0
> ```
nit: usually you only use `exit` to exit early or with a non-default code. In this case, this is technically exiting instead of letting `main` complete.
</blockquote></details>

done
___
*[build/wfa/generate_user_certificate_validator.sh, line 26 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfd5Ett8zMua-rFyUqp:-Mfd8Dh6AnkHXF_zD4H5:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1a5c7867b917d6c5056091bfce94f9b17597451c/build/wfa/generate_user_certificate_validator.sh#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> readonly 
> ```
nit: If declaring in a function, you can use local variables rather than globals.

e.g.
```
local -r root_key_file="$1"
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-27 18:26 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-MfdC6ooDiXVIPk0oMVG:b3bgq1z) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what if I just slim down openssl.cnf to just the include? That way we can `-verify_hostname` in the test. Went ahead and did that. I like that better for now.
</blockquote></details>

The issue is that we *want* the SAN to be included in our generated certs. The override was quite intentional and specifically for that purpose.

It's okay that we can't use `-verify_hostname` to verify the subject common name if a SAN is specified. In fact, it's not even required that the subject common name be a hostname (which is why I believe is one of the reasons the SAN extension was added in the first place). As it is, we have to use command output to verify the subject organization.


<!-- Sent from Reviewable.io -->

2021-07-27 22:08 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-Mfe-Bu-6_NIdq1tc_36:bhu1wou) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The issue is that we *want* the SAN to be included in our generated certs. The override was quite intentional and specifically for that purpose.

It's okay that we can't use `-verify_hostname` to verify the subject common name if a SAN is specified. In fact, it's not even required that the subject common name be a hostname (which is why I believe is one of the reasons the SAN extension was added in the first place). As it is, we have to use command output to verify the subject organization.
</blockquote></details>

Okay. Reverted openssl.cnf. I also added a comment around this.

Why do we want the SAN to be included in our generated certs?


<!-- Sent from Reviewable.io -->

2021-07-27 22:27 UTC, SanjayVas approved these changes
> Reviewed 1 of 3 files at r10, 2 of 3 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-Mfe3zBVAJzmJIQC5rOi:-Mfe3zBVAJzmJIQC5rOj:b8rvtn1) (no related file):*
Thanks for bearing with me on the macro validation and Bash scripting stuff!

---
___
*[build/wfa/generate_root_certificate_validator.sh, line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15#-MfZCeEZ4Xg2DEOtxQeM:-Mfe21Ko0t3OW92MXhyL:b-3q7l7c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fe929a41c211df2b6a661ffe426fac175a6aee77/build/wfa/generate_root_certificate_validator.sh#L19)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Okay. Reverted openssl.cnf. I also added a comment around this.

Why do we want the SAN to be included in our generated certs?
</blockquote></details>

It's used to indicate the host IP or DNS name. A cert can include SAN entries, but only one subject common name. Therefore, it has effectively replaced subject common name for specifying this information. It's practically a required extension now, as modern TLS implementations rely on it (including gRPC and browsers).


<!-- Sent from Reviewable.io -->

2021-07-27 23:14 UTC, stevenwarejones reviewed
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-27 23:15 UTC, merged