Fix potential deadlock in Spanner AsyncDatabaseClient.
world-federation-of-advertisers/common-jvm pull request #162
Opened 2022-08-25 23:48 UTC by SanjayVas

Limiting to a single transaction when using Spanner Emulator was masking an issue related to the Spanner client library's internal transaction retry logic. Aborted transactions should be retried[^1], but coroutine cancellation could prevent this from occurring.

[^1]: https://cloud.google.com/spanner/docs/transactions

2022-08-26 14:47 UTC, stevenwarejones requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`build/versions.bzl` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162#-NAPbkDR54htbo0VGFiM:-NAPbkDR54htbo0VGFiN:b-p3zqfi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/696728b12a58850e608c529d37d06c0100284d1e/build/versions.bzl#L21)):*
> ```Starlark
> PROTOBUF_VERSION = "3.20.1"
> PROTOBUF_JAVA_VERSION = PROTOBUF_VERSION
> PROTOBUF_KOTLIN_VERSION = PROTOBUF_JAVA_VERSION
> ```

are we okay with these diverging?


<!-- Sent from Reviewable.io -->

2022-08-29 18:45 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`build/versions.bzl` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162#-NAPbkDR54htbo0VGFiM:-NAerHRM5X0i8cX-uN4G:bkuh71f) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/696728b12a58850e608c529d37d06c0100284d1e/build/versions.bzl#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are we okay with these diverging?
</blockquote></details>

Protobuf changed their versioning scheme. See https://developers.google.com/protocol-buffers/docs/news/2022-05-06. e.g. the newest protobuf release is now 21.5, which corresponds to protobuf-java 3.21.5 but protobuf-python 4.21.5.

This is in preparation for dealing with that change, though we're stuck on an older version due to https://github.com/bazelbuild/rules_proto/issues/136. Added a TODO citing that bug.


<!-- Sent from Reviewable.io -->

2022-08-30 19:41 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-08-30 21:11 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-08-30 21:14 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-08-30 21:19 UTC, merged