Add Riegeli Decompressor
world-federation-of-advertisers/common-jvm pull request #175
Opened 2023-01-04 00:26 UTC by jononon

While implementing the labeling pipeline in Kotlin, I was able to write a native Kotlin Riegeli decompressor. The Riegeli compression format is used within WFA to compress the VID labeling models.

The specification for the Riegeli compression format can be found here: https://github.com/google/riegeli

I presume that common-jvm is an appropriate place to put a Riegeli decompressor as the common-cpp repo already has one: https://github.com/world-federation-of-advertisers/common-cpp/blob/main/src/main/cc/common_cpp/protobuf_util/riegeli_io.h

I can also see virtual-people-common or virtual-people-core-serving as appropriate places for this decompressor as well, should we only use riegeli compression for VID labeling. Guidance would be appreciated if this is the case.

2023-01-04 16:25 UTC, kungfucraig commented
Should we be trying to get it merged here (https://github.com/google/riegeli) instead?

2023-01-05 21:00 UTC, jononon commented
> Should we be trying to get it merged here (https://github.com/google/riegeli) instead?

I can move this there -- my primary concerns with doing this revolve around the complexity of setting up bazel in our projects to access a java version in the google/riegeli repo.

Happy to attempt to get a build working in google/riegeli if we think this is the right home.

2023-02-27 18:32 UTC, jononon commented
Rebased with master + force-pushed.

We have had a [PR open for awhile with google/riegeli](https://github.com/google/riegeli/pull/25) - no progress or comments on it at all.

2023-06-13 12:41 UTC, stevenwarejones reviewed
I suggest getting it merged here and looking to migrate it eventually to google/riegeli

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-:-NXolSrt8UDE-70x8a3B:bl23ell)* status: 0 of 11 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-13 12:47 UTC, stevenwarejones reviewed
> Reviewed 8 of 11 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jononon, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/HighwayHash.java` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXolrcP5a_cc34tn-EJ:-NXolrcP5a_cc34tn-EK:b5xz7i8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/HighwayHash.java#L17)):*
> ```Java
> package org.wfanet.measurement.common.riegeli;
> 
> //Taken from https://github.com/google/highwayhash/blob/master/java/com/google/highwayhash/HighwayHash.java
> ```

i think there should be a TODO to use google/highwayhash directly once they add bazel deps (we could help them with that too)
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXomorx5D-ds3D1MzeN:-NXomorx5D-ds3D1MzeO:b-n19k5d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L41)):*
> ```Kotlin
>  * @throws IndexOutOfBoundsException if the size of the provided ByteArray is not 8.
>  */
> fun readLittleEndian64Long(byteArray: ByteArray): Long {
> ```

should these convenience functions get moved to https://github.com/world-federation-of-advertisers/common-jvm/blob/d1145ba0f6dc93bc3334751c6f93adf22a2a24b1/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L4 @SanjayVas ?a


<!-- Sent from Reviewable.io -->

2023-06-13 18:32 UTC, SanjayVas requested changes
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @jononon, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel` line 13 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXq0jLZ7KS422k1DlSz:-NXq0jLZ7KS422k1DlT-:bpnxzeq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel#L13)):*
> ```Starlark
>     deps = [
>         ":highway_hash",
>         "@maven//:org_apache_commons_commons_compress",
> ```

All Maven targets get an alias under the `imports` tree instead of being referenced directly.



_Code quote:_
```Starlark
"@maven//:org_apache_commons_commons_compress",
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXq0v6027j6xLg1x0iv:-NXq0v6027j6xLg1x0iw:bf3aojb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel#L14)):*
> ```Starlark
>         ":highway_hash",
>         "@maven//:org_apache_commons_commons_compress",
>         "@maven//:org_brotli_dec",
> ```

I don't see this dependency being used. It looks like all the Brotli references are from commons-compress instead.



_Code quote:_
```Starlark
"@maven//:org_brotli_dec",
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/HighwayHash.java` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXolrcP5a_cc34tn-EJ:-NXpz0ZWDAiVxERERFUB:bttsohn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/HighwayHash.java#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think there should be a TODO to use google/highwayhash directly once they add bazel deps (we could help them with that too)
</blockquote></details>

If we copy a file from an external source, it needs to be in the `third_party` tree so it's extra clear that it has its own license/copyright. Our linters know not to touch anything in that tree.

Note that we should avoid directly copying anything into third_party when at all possible, as that means we're now redistributing something. A better solution would be to add this as a repo dependency. Even if it doesn't have Bazel support, we can supply our own BUILD/WORKSPACE using the appropriate attributes in [`http_archive`](https://bazel.build/rules/lib/repo/http#http_archive)
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXomorx5D-ds3D1MzeN:-NXq-3Kl3gbtFo3Hsupv:b-5fw86a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should these convenience functions get moved to https://github.com/world-federation-of-advertisers/common-jvm/blob/d1145ba0f6dc93bc3334751c6f93adf22a2a24b1/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L4 @SanjayVas ?a
</blockquote></details>

Yes. Note that we also use `ByteString` or `ByteBuffer` instead of `ByteArray` when possible (sometimes you need to support `ByteArray` to avoid unnecessary copies).
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXpyVAe0EugxwSUjIlf:-NXpyVAe0EugxwSUjIlg:bymhjhe) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L24)):*
> ```Kotlin
> private const val DATA_PATH = "src/test/proto/wfa/measurement/common/riegeli/test_data"
> 
> @RunWith(JUnit4::class)
> ```

Try to mirror the tests that exist in the official Riegeli impl. This means that any test data we use should come from that repo.


<!-- Sent from Reviewable.io -->

2023-07-21 22:59 UTC, kungfucraig requested changes
The implementation seems correct. Left a few comments. 

I think it would be good to leave TODOs for the chunk types we are not implementing. 

Otherwise I think the main things are: 1) taking a proper dep on Highwayhash vs. inlining it; and 2) having a more comprehensive set of tests.

> Reviewed 1 of 11 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-:-N_udYNQ78vNXC8LgM3H:b-ds9znr)* status: 9 of 11 files reviewed, 10 unresolved discussions (waiting on @jononon, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/HighwayHash.java` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXolrcP5a_cc34tn-EJ:-N_F10Rd3wlcFLVuYLt8:b8uh4qt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/HighwayHash.java#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If we copy a file from an external source, it needs to be in the `third_party` tree so it's extra clear that it has its own license/copyright. Our linters know not to touch anything in that tree.

Note that we should avoid directly copying anything into third_party when at all possible, as that means we're now redistributing something. A better solution would be to add this as a repo dependency. Even if it doesn't have Bazel support, we can supply our own BUILD/WORKSPACE using the appropriate attributes in [`http_archive`](https://bazel.build/rules/lib/repo/http#http_archive)
</blockquote></details>

+1 @SanjayVas 
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uYBbtBz9Rdtjh2avo:-N_uYBbtBz9Rdtjh2avp:b-mtyeg8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L101)):*
> ```Kotlin
>     result = result or (b and 0x7F shl shift)
>     shift += 7
>   } while (b and 0x80 != 0)
> ```

What's the "0x80 != 0" for?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uYZuS2eGFxO9PIPX1:-N_uYZuS2eGFxO9PIPX2:b-q9xjd0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L111)):*
> ```Kotlin
>  * @return A HighwayHash object with specified key.
>  */
> fun generateHighwayHash(): HighwayHash {
> ```

nit: s/generate/build. 
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 235 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_u_Zz40DdKOZGnh2fr:-N_u_Zz40DdKOZGnh2fs:b8m98to) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L235)):*
> ```Kotlin
>         highwayHash.updatePacket(headerData, 0)
> 
>         val hashedDataString = java.lang.Long.toHexString(highwayHash.finalize64())
> ```

Why do we need to convert to a hex string vs. comparing the longs?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 439 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uc6HC2aRr_hDQFiwK:-N_uc6HC2aRr_hDQFiwL:b-31okcu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L439)):*
> ```Kotlin
>        * Compares the headerHash element of the block's header to a highway hash of the block's other header elements.
>        *
>        * @param headerHash      64-bit ByteArray containing a HighwayHash of the other chunk header elements
> ```

This headerHash is of  "the rest of the header (`previous_chunk` and `next_chunk`)". Maybe you have a copy/paste error from chunk here?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 483 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_ud1fADohDF3Dt2oTj:-N_ud1fADohDF3Dt2oTk:brqq8dl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L483)):*
> ```Kotlin
>         records.addAll(chunk.getRecords())
>       } else {
>         println("NON RECORD CHUNK -- Chunk type: ${chunk.chunkType[0]}")
> ```

Is this the right behavior?
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXpyVAe0EugxwSUjIlf:-N_uWaFX1DrXpGMcoR9Q:b-j6cvl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Try to mirror the tests that exist in the official Riegeli impl. This means that any test data we use should come from that repo.
</blockquote></details>

+1 @SanjayVas 

I'd like to see tests for the free helper functions too (e.g. getVarInt)


<!-- Sent from Reviewable.io -->

2023-08-03 18:18 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 4 of 19 files reviewed, 11 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 121 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NawZdja-EnbjgB5l2YQ:-NawZdja-EnbjgB5l2YR:b-lkofxf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7882628d5e56d5076b50a06433ffcd6ff576a747/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L121)):*
> ```Kotlin
> }
> 
> fun ByteString.withTrailingPadding(paddedSize: Int): ByteString {
> ```

Working on unit tests for new functions in bytes.kt
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel` line 13 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXq0jLZ7KS422k1DlSz:-NarPiqS9q5ieBZRxLyJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All Maven targets get an alias under the `imports` tree instead of being referenced directly.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXq0v6027j6xLg1x0iv:-NahE8AD5CP_yze8Y3hr:bvmweot) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see this dependency being used. It looks like all the Brotli references are from commons-compress instead.
</blockquote></details>

org_brotli_dec is an optional dependency of org_apache_commons_commons_compress (https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.23.0). We need to explicitly include org_brotli_dec in order for commons-compress to work properly. Removing org_brotli_dec causes the code to stop working.

![Screen Shot 2023-07-31 at 11.54.10 AM.png](https://files.reviewableusercontent.io/images/reviewable/5778251/KsM6-X0HZlvA85s0JnGZAvpX/Screen%20Shot%202023-07-31%20at%2011.54.10%20AM.png) (https://commons.apache.org/proper/commons-compress/limitations.html)

We will also need to include zstd-jni for zstd compression to work properly.
![Screen Shot 2023-07-31 at 11.54.52 AM.png](https://files.reviewableusercontent.io/images/reviewable/5778251/mD_xieccSbFxwWx7pQa_9kT-/Screen%20Shot%202023-07-31%20at%2011.54.52%20AM.png)
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXomorx5D-ds3D1MzeN:-NasyiMp5vKTONC08UsW:b-6coya8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. Note that we also use `ByteString` or `ByteBuffer` instead of `ByteArray` when possible (sometimes you need to support `ByteArray` to avoid unnecessary copies).
</blockquote></details>

Refactored the code to avoid using ByteArray except for some copying operations. 
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uYBbtBz9Rdtjh2avo:-Nahg5Q8Asnoo5GizXQB:b-zaiju2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L101)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What's the "0x80 != 0" for?
</blockquote></details>

Kotlin infix functions (including 'and' and 'or') have higher precedence than equality operators. This line should be read as `while ((b and 0x80) != 0)`.

The while statement ends the loop when the first bit in the number is 0.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uYZuS2eGFxO9PIPX1:-NawblC9EKkfh3NqaQ9m:b-ivy5b9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L111)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

nit: s/generate/build. 
</blockquote></details>

Unsure what this means
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 235 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_u_Zz40DdKOZGnh2fr:-Nawa9ZZ4AyGDKdsPXKm:bhnu9qu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L235)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why do we need to convert to a hex string vs. comparing the longs?
</blockquote></details>

Done: No need - we can compare the longs
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 439 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uc6HC2aRr_hDQFiwK:-Nawad1k4Gg8gXNPeXaq:bmabgbm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L439)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This headerHash is of  "the rest of the header (`previous_chunk` and `next_chunk`)". Maybe you have a copy/paste error from chunk here?
</blockquote></details>

Done: Yep - copy paste error.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 483 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_ud1fADohDF3Dt2oTj:-NahhTW22oL9kHRBL7GO:b-tthmx7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L483)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is this the right behavior?
</blockquote></details>

[Chunk types in the riegeli standard](https://github.com/google/riegeli/blob/master/doc/riegeli_records_file_format.md#chunk-data) are 
0x73 - file signature - present at the beginning of the file, encodes no records, is ignored
0x6d - file metadata - provides information describing the records, not necessary to read the records
0x70 - padding - encodes no records and only occupies file space
0x72 - simple chunk with records - stores record sizes and concatenated record contents
0x74 - transposed chunk with records - no documentation provided for the format of this chunk, unused in WFA

As far as I can tell, we only need to read 0x72 type. All other chunk types can be ignored. As implementation for 0x74 is not available, we can safely ignore.

I updated this line to use the logger and added comments for the unimplemented types.
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXpyVAe0EugxwSUjIlf:-NaszyKaATbipXA4bjDS:b-vhwrj9) ([raw file](https://github.com/wo [...]

2023-08-03 20:27 UTC, kungfucraig requested changes
> Reviewed 3 of 11 files at r1, 11 of 15 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 16 of 19 files reviewed, 8 unresolved discussions (waiting on @jononon, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXq0v6027j6xLg1x0iv:-Nax3BA-BVMUcOG-TQ0j:b-6jqzcm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/BUILD.bazel#L14)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

org_brotli_dec is an optional dependency of org_apache_commons_commons_compress (https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.23.0). We need to explicitly include org_brotli_dec in order for commons-compress to work properly. Removing org_brotli_dec causes the code to stop working.

![Screen Shot 2023-07-31 at 11.54.10 AM.png](https://files.reviewableusercontent.io/images/reviewable/5778251/KsM6-X0HZlvA85s0JnGZAvpX/Screen%20Shot%202023-07-31%20at%2011.54.10%20AM.png) (https://commons.apache.org/proper/commons-compress/limitations.html)

We will also need to include zstd-jni for zstd compression to work properly.
![Screen Shot 2023-07-31 at 11.54.52 AM.png](https://files.reviewableusercontent.io/images/reviewable/5778251/mD_xieccSbFxwWx7pQa_9kT-/Screen%20Shot%202023-07-31%20at%2011.54.52%20AM.png)

</blockquote></details>

Can you note that in a comment and move the dependency to a "runtime_deps"?

See: https://bazelbuild.github.io/rules_kotlin/kotlin.html
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uYBbtBz9Rdtjh2avo:-Nax3g5zEUYs7dShyJa1:b-48qina) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L101)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Kotlin infix functions (including 'and' and 'or') have higher precedence than equality operators. This line should be read as `while ((b and 0x80) != 0)`.

The while statement ends the loop when the first bit in the number is 0.
</blockquote></details>

I think maybe this got relocated to "bytes.kt," but either way a comment in the code would be helpful.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-N_uYZuS2eGFxO9PIPX1:-Nax3qEy-t-VZFzQ8H6x:bf308fw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L111)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Unsure what this means
</blockquote></details>

Sorry, it's a vi editor command that says replace the string "generate" with "build". Basically just rename this to "buildHighwayHash." :)


<!-- Sent from Reviewable.io -->

2023-08-04 22:28 UTC, SanjayVas requested changes
> Reviewed 9 of 15 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 17 of 19 files reviewed, 18 unresolved discussions (waiting on @jononon and @stevenwarejones)

___
*[`build/com_google_highwayhash/BUILD.external` line 5 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1UPPu8q1H6T1GG0L0:-Nb1UPPu8q1H6T1GG0L1:b43u40c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/build/com_google_highwayhash/BUILD.external#L5)):*
> ```
> java_library(
>     name = "highway_hash",
>     srcs = glob(["**/*.java"]),
> ```

I think this is just the one source file.



_Suggestion:_
```
["java/com/google/highwayhash/HighwayHash.java"]
```
___
*[`build/com_google_highwayhash/repo.bzl` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1UbIC-nfikTuRj0XG:-Nb1UbIC-nfikTuRj0XH:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/build/com_google_highwayhash/repo.bzl#L1)):*
> ```Starlark
> # Copyright 2021 The Cross-Media Measurement Authors
> ```

nit



_Suggestion:_
```Starlark
2023
```
___
*[`build/com_google_highwayhash/repo.bzl` line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1Ut783qtNYGZ-t0zf:-Nb1Ut783qtNYGZ-t0zg:bjz2cd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/build/com_google_highwayhash/repo.bzl#L21)):*
> ```Starlark
>     maybe(
>         http_archive,
>         name = "com_google_highwayhash",
> ```

Use strip_prefix to remove the wrapper directory.
___
*[`build/com_google_highwayhash/repo.bzl` line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1Uyp-96MLmKv7r4pZ:-Nb1Uyp-96MLmKv7r4p_:b-edlvl4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/build/com_google_highwayhash/repo.bzl#L23)):*
> ```Starlark
>         name = "com_google_highwayhash",
>         sha256 = "5380cb7cf19e7c9591f31792b7794d48084f6a3ab7c03d637cd6a32cf2ee8686",
>         url = "https://github.com/google/highwayhash/archive/a7f68e2f95fac08b24327d74747521cf634d5aff.zip",
> ```

nit: we tend to use the tarball



_Suggestion:_
```Starlark
.tar.gz
```
___
*[`imports/java/com/github/luben/BUILD.bazel` line 4 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1aUI10okJ9t7Y1jN-:-Nb1aUI10okJ9t7Y1jN0:b-7dpqeu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/imports/java/com/github/luben/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "zstd-jni",
> ```

This should be named `zstd` and be in a `zstd` Bazel package. See the other comment re: Bazel package paths.



_Code quote:_
```Starlark
zstd-jni
```
___
*[`imports/java/org/brotli/BUILD.bazel` line 4 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1_qHgAkEnpoii6pEm:-Nb1_qHgAkEnpoii6pEn:b-n9t5ji) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/imports/java/org/brotli/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "dec",
> ```

The Bazel package path relates to the Java package path (this may or may not be represented in the Maven coordinates. You need to inspect the actual JAR.) Therefore this should be in a `dec` subpackage, as it looks like the Maven artifact fully defines that Java package.
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 350 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1WCg-2z1a2Bi8vul_:-Nb1WCg-2z1a2Bi8vula:b-lbkrta) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L350)):*
> ```Kotlin
>  * @throws IndexOutOfBoundsException if the size of the provided ByteArray is not 8.
>  */
> fun readLittleEndian64Long(byteString: ByteString): Long {
> ```

You can just call `ByteString.toLong` which is already defined in this file, passing `ByteOrder.LITTLE_ENDIAN`.
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 367 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1WRQX53wA1cqUqCYs:-Nb1WRQX53wA1cqUqCYt:b-8lu7s4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L367)):*
> ```Kotlin
>  * @throws IndexOutOfBoundsException if the size of the provided ByteArray is not 8.
>  */
> fun readLittleEndian64Int(byteString: ByteString): Int {
> ```

More explicit for callers to just chain existing conversions. e.g.

```kotlin
byteString.toLong(ByteOrder.LITTLE_ENDIAN).toInt()
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 378 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1WlDcBUhPK16lTuT6:-Nb1WlDcBUhPK16lTuT7:b-f4coqi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L378)):*
> ```Kotlin
>  * @throws IndexOutOfBoundsException if the size of the provided ByteArray is not 7.
>  */
> fun readLittleEndian56Int(byteString: ByteString): Int {
> ```

Follow existing patterns. Since a 56-bit integer cannot fit into an `Int`, return this as a `Long` and let the caller convert to `Int` if necessary. Also document whether the representation is signed and if so note if it uses anything other than the standard two's complement.



_Suggestion:_
```Kotlin
fun ByteString.toLong56Bit(byteOrder: ByteOrder)
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 390 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1XpjJAdwl1OHeJKvT:-Nb1XpjJAdwl1OHeJKvU:b-x04gil) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L390)):*
> ```Kotlin
>  * Varints are variable-width integers.
>  *
>  * Code snippet taken from
> ```

Don't just copy code snippets from GitHub into our own code, which uses our own copyright and license headers. Reference them as repository deps if you can. As a last resort, copy them into the third_party tree with appropriate license info.

Note that in this case however, [varint encoding](https://protobuf.dev/programming-guides/encoding/) is used by the protobuf library which we already depend on. See if what you need is in https://github.com/search?q=repo%3Aprotocolbuffers%2Fprotobuf%20path%3A%2F%5Ejava%5C%2F%2F%20varint&type=code
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXomorx5D-ds3D1MzeN:-Nb1amx61fa1xrA8T6MH:b-69fznx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L41)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Refactored the code to avoid using ByteArray except for some copying operations. 
</blockquote></details>

Assuming you do actually need to read the entire stream into memory (generally a bad idea if you can avoid it, but okay if it's a small chunk), then you don't want to do it byte-by-byte as that's extremely inefficient. The general idea with `java.nio` is to avoid blocking I/O as much as possible, and to have tha [...]

2023-08-04 22:48 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 17 of 19 files reviewed, 19 unresolved discussions (waiting on @jononon and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 131 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1ftPt7sE6TUGu_lRh:-Nb1ftPt7sE6TUGu_lRi:b4wh20c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L131)):*
> ```Kotlin
>       output.toByteString()
>     })
> }
> ```

Writing one byte at a time is inefficient.



_Suggestion:_
```Kotlin
fun ByteString.withTrailingPadding(paddedSize: Int): ByteString {
  if (size >= paddedSize) {
    return this
  }

  val padding = ByteArray(paddedSize - size)
  return concat(ByteString.copyFrom(padding))
}
```


<!-- Sent from Reviewable.io -->

2023-08-15 18:17 UTC, SanjayVas requested changes
> Reviewed 3 of 11 files at r1, 1 of 2 files at r2, 5 of 15 files at r4, 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 10 unresolved discussions (waiting on @jononon, @kungfucraig, and @stevenwarejones)

___
*[`build/com_google_highwayhash/BUILD.external` line 5 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1UPPu8q1H6T1GG0L0:-NbuKoWvBXHqKvigj92I:b-kmsf8p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/build/com_google_highwayhash/BUILD.external#L5)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You don't need the glob for a single file. Just `srcs = ["java/com/google/highwayhash/HighwayHash.java"],`
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 347 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NbuLYaHE9WtPdDXDC16:-NbuLYaHE9WtPdDXDC17:b-tkzzf6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8cc8cbe2ce93ff95cd97f2318fc34788220a2618/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L347)):*
> ```Kotlin
>  * @param inputStream The input stream from which the varint should be read.
>  * @return The 64-bit varint which has been read from the input stream. This is returned as a Long.
>  */
> ```

All of the references to an input stream are incorrect, as this function operates on a param of type `ByteBuffer` named `byteBuffer`.

This should also document whether this is reading a signed vs. unsigned varint as they are encoded differently. Linking the documentation for varint encoding would be a good idea.



_Code quote:_
```Kotlin
/**
 * Reads a varint from an InputStream.
 * Varints are variable-width integers, supporting up to 64-bit integers.
 *
 * @param inputStream The input stream from which the varint should be read.
 * @return The 64-bit varint which has been read from the input stream. This is returned as a Long.
 */
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 349 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NbuN1oI4zisSGGYfGA1:-NbuN1oI4zisSGGYfGA2:b-fafmjp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8cc8cbe2ce93ff95cd97f2318fc34788220a2618/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L349)):*
> ```Kotlin
>  */
> 
> fun getVarLong(byteBuffer: ByteBuffer): Long {
> ```

I think this might make more sense as an extension method.



_Suggestion:_
```Kotlin
fun ByteBuffer.getVarInt64(): Long
```
___
*[`src/test/kotlin/org/wfanet/measurement/common/BytesTest.kt` line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NbuO3JY3_BzGSeIZVfh:-NbuO3JZ3alp-wgZVrd5:b-k9kluj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8cc8cbe2ce93ff95cd97f2318fc34788220a2618/src/test/kotlin/org/wfanet/measurement/common/BytesTest.kt#L69)):*
> ```Kotlin
> 
>   @Test
>   fun `ByteString with trailing padding on empty ByteString`() = runBlocking {
> ```

You only need to use this if your test method calls suspend functions. I don't spot any here at first glance.



_Code quote:_
```Kotlin
runBlocking
```
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXpyVAe0EugxwSUjIlf:-NbuP4Zy8CVIOgj56o0r:bwhop9v) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L24)):*
> Try to mirror the tests that exist in the official Riegeli impl. This means that any test data we use should come from that repo.

Just to confirm, did you copy the test data from the official repo? As stated in the initial comment the idea is that we shouldn't have our own custom tests but should instead ensure that our implementation would pass the official repo tests if they were written in this language.


<!-- Sent from Reviewable.io -->

2023-08-15 18:51 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`build/com_google_highwayhash/BUILD.external` line 5 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nb1UPPu8q1H6T1GG0L0:-NbuWu2_ErNfNPPM6-JE:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e096b124351260a200f84d1dff2c363b9168f4d7/build/com_google_highwayhash/BUILD.external#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need the glob for a single file. Just `srcs = ["java/com/google/highwayhash/HighwayHash.java"],`
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 347 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NbuLYaHE9WtPdDXDC16:-NbuVRiQ-GZzXO2TArV8:b1ib1ov) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8cc8cbe2ce93ff95cd97f2318fc34788220a2618/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L347)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All of the references to an input stream are incorrect, as this function operates on a param of type `ByteBuffer` named `byteBuffer`.

This should also document whether this is reading a signed vs. unsigned varint as they are encoded differently. Linking the documentation for varint encoding would be a good idea.
</blockquote></details>

Done - changed the comments to be accurate, included that the varints are unsigned and provided link to the varint spec used.

I also updated the comments on riegeli.kt to remove any incorrect references to ByteArrays.
___
*[`src/main/kotlin/org/wfanet/measurement/common/Bytes.kt` line 349 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NbuN1oI4zisSGGYfGA1:-NbuSI0aBDueOcrjw6mP:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8cc8cbe2ce93ff95cd97f2318fc34788220a2618/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L349)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this might make more sense as an extension method.
</blockquote></details>

Done
___
*[`src/test/kotlin/org/wfanet/measurement/common/BytesTest.kt` line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NbuO3JY3_BzGSeIZVfh:-NbuRvb43f0Am45afneV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8cc8cbe2ce93ff95cd97f2318fc34788220a2618/src/test/kotlin/org/wfanet/measurement/common/BytesTest.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You only need to use this if your test method calls suspend functions. I don't spot any here at first glance.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXpyVAe0EugxwSUjIlf:-NbuQjplB_zZnrlK59ZB:b-z7jim2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Try to mirror the tests that exist in the official Riegeli impl. This means that any test data we use should come from that repo.

Just to confirm, did you copy the test data from the official repo? As stated in the initial comment the idea is that we shouldn't have our own custom tests but should instead ensure that our implementation would pass the official repo tests if they were written in this language.
</blockquote></details>

Sorry - you're correct, my mistake. Was responding to Craig with regards to tests for helper functions which I wrote. Your original comment was hidden when I responded. Still working on tests.


<!-- Sent from Reviewable.io -->

2023-08-15 23:29 UTC, kungfucraig reviewed
> Reviewed 1 of 2 files at r2, 2 of 15 files at r4, 4 of 8 files at r6, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-22 18:25 UTC, stevenwarejones reviewed
> Reviewed 1 of 11 files at r1, 1 of 2 files at r2, 8 of 15 files at r4, 4 of 8 files at r6, 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 8 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-08-23 23:48 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 14 of 24 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NXpyVAe0EugxwSUjIlf:-NbznUXQDMB96GLz6mYx:b-xn66ng) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b083535b4e3cad4073494f2ff80acd6dfeda1d9f/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L24)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Sorry - you're correct, my mistake. Was responding to Craig with regards to tests for helper functions which I wrote. Your original comment was hidden when I responded. Still working on tests.
</blockquote></details>

I can't truly emulate their tests for a few reasons:
- Most of their tests involve writing a riegeli file and then reading it. This PR only supports reading so I have provided two riegeli files (one normal, one corrupted) which are what the google/riegeli repo is creating during runtime and reading from. 
- google/riegeli implementation covers reading metadata, ours does not as it is not nessacary for reading riegeli files. Unit tests from google/riegeli where this functionality is being tested were not emulated in this PR.
- google/riegeli is structured more like a buffer or stream which can seek, rewind, or search for a record. The way I have written this reader does not do this, we read the whole file in one go and provide a list of messages as a result. Unit tests from google/riegeli where this functionality is being tested were not emulated in this PR.

I have emulated all of the tests which have to do with reading both corrupted and non-corrupted record files. 

The unit tests in the google/riegeli repo can be found here: https://github.com/google/riegeli/blob/master/python/riegeli/records/tests/records_test.py


<!-- Sent from Reviewable.io -->

2023-08-24 22:07 UTC, SanjayVas requested changes
> Reviewed 2 of 4 files at r8, 4 of 13 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 19 unresolved discussions (waiting on @jononon and @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 33 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQbND7Rn7owYbWEKh:-NcdQbND7Rn7owYbWEKi:b-bi43lb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L33)):*
> ```Kotlin
> import org.apache.commons.compress.compressors.zstandard.ZstdCompressorInputStream
> import org.apache.commons.compress.utils.CountingInputStream
> import org.wfanet.measurement.common.*
> ```

Wildcard imports are not allowed. Import each symbol explicitly.

See https://developer.android.com/kotlin/style-guide#import_statements



_Code quote:_
```Kotlin
import org.wfanet.measurement.common.*
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 36 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQKZP8JN9jKiWu0qs:-NcdQKZP8JN9jKiWu0qt:b-v2tuvl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L36)):*
> ```Kotlin
> 
> 
> // Package-level constant representing the fixed-size of a block within a Riegeli compressed file.
> ```

1. Java and Kotlin have different default visibility. In Kotlin, this is public rather than package-private.
2. Why is the intent for this to be package-level at all? Is it not used exclusively inside of `Riegeli`?



_Code quote:_
```Kotlin
Package-level constant
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQE6VB1lRDsjfOcu5:-NcdQE6VB1lRDsjfOcu6:b-vzr9mv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L37)):*
> ```Kotlin
> 
> // Package-level constant representing the fixed-size of a block within a Riegeli compressed file.
> const val kBlockSize = 1 shl 16
> ```

Kotlin constants use `SCREAMING_SNAKE_CASE` without any prefix.



_Suggestion:_
```Kotlin
BLOCK_SIZE
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 45 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQqHk9ZTZ_osDdtoF:-NcdQqHk9ZTZ_osDdtoG:brkdplg) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L45)):*
> ```Kotlin
>  * @return A HighwayHash object with specified key.
>  */
> fun buildHighwayHash(): HighwayHash {
> ```

Don't add public non-extension functions to the package namespace. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 55 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdNvQhCu3BPVLezOYB:-NcdNvQhCu3BPVLezOYC:be0grlm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L55)):*
> ```Kotlin
>  * https://github.com/google/riegeli/blob/master/doc/riegeli_records_file_format.md
>  */
> class Riegeli {
> ```

I'm not spotting any state. Maybe this should be an object instead of a class.



_Suggestion:_
```Kotlin
object Riegeli {
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 70 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdKwsz5v2o-OVQvnBX:-NcdKwt-9_neC9n1zWZH:b-i5pvjz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L70)):*
> ```Kotlin
>    *                        (dataSize, dataHash, chunkType, numRecords, and decodedDataSize).
>    * @param dataSize        ByteString representing the size of the chunk data, excluding intervening block headers,
>    *                        as a 64-bit, little-endian long.
> ```

The comment states that this is both a Long and a ByteString. Both cannot be true. Are you just trying to say this is a 64-bit integer in little endian byte order? If so, is it signed or unsigned?



_Code quote:_
```Kotlin
as a 64-bit, little-endian long
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 72 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdLnirEcBskNCWMy2s:-NcdLnisCGx4VYBwg4SO:btbzzdm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L72)):*
> ```Kotlin
>    *                        as a 64-bit, little-endian long.
>    * @param dataHash        ByteString containing a HighwayHash of the data within the chunk.
>    * @param chunkType       ByteString containing a single byte which represents the chunk type.
> ```

If it's just a single byte, use `Byte` as that's also an immutable type.



_Code quote:_
```Kotlin
single byte
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 83 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdRL0O48n65Bx1Dxh5:-NcdRL0O48n65Bx1Dxh6:bngnmfi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L83)):*
> ```Kotlin
>    * @param data            ByteBuffer with the chunk's compressed data. The buffer's size is represented by dataSize.
>    */
>   private class Chunk private constructor(val headerHash: ByteString,
> ```

nit: you don't need to specify `private constructor` when the class is already private.



_Code quote:_
```Kotlin
 private constructor
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 92 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdO7aD5qj9-r_SB9__:-NcdO7aD5qj9-r_SB9_a:b-dp9d6t) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L92)):*
> ```Kotlin
> 
> 
>     companion object {
> ```

nit: companion objects are conventionally declared at the end of a class rather than the beginning
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 108 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdRY_i9umeCPDLHV86:-NcdRY_i9umeCPDLHV87:beq303g) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L108)):*
> ```Kotlin
>        * @return A new chunk object as read from the inputStream.
>        */
>       fun fromInputStream(inputStream: CountingInputStream): Chunk? {
> ```

nit: I would expect a function of this name to exhaust the input stream rather than just reading a single chunk from it.  Maybe just `readFrom` so the caller would use `Chunk.readFrom(input)`.



_Suggestion:_
```Kotlin
readFrom
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 296 at r9](https://reviewable.io/reviews/world-federation-of-advertise [...]

2023-08-25 20:39 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 14 of 24 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 33 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQbND7Rn7owYbWEKh:-NcdcXYf1NU2OZAqhuLr:bn8f9sx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wildcard imports are not allowed. Import each symbol explicitly.

See https://developer.android.com/kotlin/style-guide#import_statements
</blockquote></details>

Done. - Sorry, IntelliJ was pushing the imports under a wildcard. Fixed.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 36 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQKZP8JN9jKiWu0qs:-NcdczFY-_Aone4uIxit:b-fi5zs1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Java and Kotlin have different default visibility. In Kotlin, this is public rather than package-private.
2. Why is the intent for this to be package-level at all? Is it not used exclusively inside of `Riegeli`?
</blockquote></details>

Done This should be private - added the private keyword and fixed the comment.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQE6VB1lRDsjfOcu5:-NcddAnt78r-6UET3OC2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Kotlin constants use `SCREAMING_SNAKE_CASE` without any prefix.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 45 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdQqHk9ZTZ_osDdtoF:-Ncddiry0BGidNdD1L4h:b7m4zxj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't add public non-extension functions to the package namespace. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
</blockquote></details>

Done - OK, made this a private function
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 55 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdNvQhCu3BPVLezOYB:-NcddvIdB-WVpbCBGsHB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not spotting any state. Maybe this should be an object instead of a class.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 70 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdKwsz5v2o-OVQvnBX:-Ncde34WB-_wxc0o58DJ:bmmrojo) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The comment states that this is both a Long and a ByteString. Both cannot be true. Are you just trying to say this is a 64-bit integer in little endian byte order? If so, is it signed or unsigned?
</blockquote></details>

Yes - was basically trying to say that the data stored in the bytestring is a 64-bit int in little endian order, unsigned. I have changed the comments to be more clear. Is the new language acceptable?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 72 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdLnirEcBskNCWMy2s:-Ncdf9mL4DjA9Nd7EaDG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If it's just a single byte, use `Byte` as that's also an immutable type.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 83 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdRL0O48n65Bx1Dxh5:-NcdfSFx3h94Tl1uOtIU:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you don't need to specify `private constructor` when the class is already private.
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 92 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdO7aD5qj9-r_SB9__:-Ncdh1iaEC-M0I9BWkiZ:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: companion objects are conventionally declared at the end of a class rather than the beginning
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 108 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdRY_i9umeCPDLHV86:-NcdhBWQ1jhQXXvwRFzJ:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I would expect a function of this name to exhaust the input stream rather than just reading a single chunk from it.  Maybe just `readFrom` so the caller would use `Chunk.readFrom(input)`.
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 296 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdNB7L8hI1nCxQcQFE:-NceFukW6CfOV-Ts4moo:b-4ysrs6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L296)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this a `LinkedList`, or a `List` at all? It should be a structure that lets you iterate over the entries without having to have all of them in memory at once. e.g. `Sequence`.
</blockquote></details>

Done: Wow! [...]

2023-08-28 15:15 UTC, kungfucraig approved these changes
> Reviewed 6 of 13 files at r9, 1 of 2 files at r10, 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 13 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-08-29 20:37 UTC, SanjayVas requested changes
> Reviewed 1 of 4 files at r8, 4 of 13 files at r9, 1 of 2 files at r10, 8 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 20 unresolved discussions (waiting on @jononon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 70 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdKwsz5v2o-OVQvnBX:-Nd1YF6i9PRNc1nLROGJ:bhw0w4y) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L70)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Yes - was basically trying to say that the data stored in the bytestring is a 64-bit int in little endian order, unsigned. I have changed the comments to be more clear. Is the new language acceptable?
</blockquote></details>

Close. The issue is with the term "long", which refers to a language-specific type with implied size, encoding, etc. I believe you mean "integer".
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 83 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdRL0O48n65Bx1Dxh5:-Nd1lVBFAyCOL24UADq5:bst0fkr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L83)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry, I didn't realize the constructor was private to indicate that the factory function should be used instead. My mistake. Even though it may not do anything when all the callers are in the same file, it does indeed make sense as a way to indicate intent.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 296 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdNB7L8hI1nCxQcQFE:-Nd1sAMaBiJeHtJ_TwnZ:b-defoe8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L296)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Done: Wow! Did not know these were a thing - I moved the logic over to sequences.
</blockquote></details>

Sequence builders are similar in concept to generators in languages like Python or JavaScript.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 465 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdZuaq32LqCVgQflEV:-Nd1mKYz2f56wO9zTHNj:b39h2z8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L465)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

I changed the `readCompressedInputStreamWithRecords`  method to use the `autocloseable.use` function. The `readCompressedFileWithRecords` method just calls`readCompressedInputStreamWithRecords` and passes the input stream. I get errors if both methods are using `AutoCloseable.use`. Is this an acceptable solution?
</blockquote></details>

See my other comment. Generally the code that creates the input stream is responsible for closing it.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 39 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1VpnBERTw3N1BF4cH:-Nd1VpnBERTw3N1BF4cI:blgje3e) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L39)):*
> ```Kotlin
> 
> 
> //Constant representing the fixed-size of a block within a Riegeli compressed file.
> ```

Use KDoc syntax for properties. See https://developer.android.com/kotlin/style-guide#documentation
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 40 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1WAzZ3lD22LeTNM8Q:-Nd1WAzZ3lD22LeTNM8R:b-8v078d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L40)):*
> ```Kotlin
> 
> //Constant representing the fixed-size of a block within a Riegeli compressed file.
> private const val BLOCK_SIZE = 1 shl 16
> ```

Any reason why this isn't defined inside the Riegeli object?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 48 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1W3rFBSWbbGWmikcH:-Nd1W3rFBSWbbGWmikcI:b-8v078d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L48)):*
> ```Kotlin
>  * @return A HighwayHash object with specified key.
>  */
> private fun buildHighwayHash(): HighwayHash {
> ```

Any reason why this isn't defined inside the Riegeli object?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 69 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XYR31a5uGA9Ky9jv:-Nd1XYR31a5uGA9Ky9jw:b-jfmuhl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L69)):*
> ```Kotlin
>     return sequence<ByteString> {
> 
>       CountingInputStream(incomingInputStream).use { inputStream ->
> ```

If your function takes in an input stream, the general convention is that the caller (i.e. whatever opens the stream) is responsible for closing it. CountingInputStream.close just delegates to the `close` method of the wrapped input stream.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 71 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1v6D87V1XNEjHcZ40:-Nd1v6D87V1XNEjHcZ41:b-op2qlv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L71)):*
> ```Kotlin
>       CountingInputStream(incomingInputStream).use { inputStream ->
> 
>         BlockHeader.fromInputStream(inputStream)
> ```

Just to make sure, is it intentional that we're reading this header and then throwing it away? If so, leave a comment so it's clear.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 78 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1vg1S6K9stYPLAny2:-Nd1vg1S6K9stYPLAny3:biduwb1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L78)):*
> ```Kotlin
>           //Chunk type is simple chunk with records (0x72)
>           if (chunk.chunkType == 0x72.toByte()) {
>             logger.info("RECORD CHUNK -- Chunk type: ${chunk.chunkType}")
> ```

Use the overload which takes in a lambda. This way the string doesn't even need to be constructed unless the logging configuration includes logs at this level.

I also think that `INFO` might be too coarse a logging level for this code and we should probably use `DEBUG` (`INFO` is the default level for all of our `org.wfanet` code, so anything at that level or higher should be generally useful in production). We can always set the logging level to include these in [...]

2023-08-30 01:04 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 18 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 70 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdKwsz5v2o-OVQvnBX:-Nd2p3gPCLhn4Lm6Ls0F:b-jdl5jf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Close. The issue is with the term "long", which refers to a language-specific type with implied size, encoding, etc. I believe you mean "integer".
</blockquote></details>

Ah - replaced all the 'long' occurrences with 'integer'.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 83 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdRL0O48n65Bx1Dxh5:-Nd2INup8YNVJPHGbU1u:b-1phmsg) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, I didn't realize the constructor was private to indicate that the factory function should be used instead. My mistake. Even though it may not do anything when all the callers are in the same file, it does indeed make sense as a way to indicate intent.
</blockquote></details>

Done - gotcha, put it back. That was my intent originally - I had completely forgotten.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 465 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-NcdZuaq32LqCVgQflEV:-Nd2iS8f7vm8jJBiiRkj:b-1hb9aq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3239d582abbbc3f9a641dbf127913fb3d15fe3d7/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L465)):*
Gotcha - made some changes detailed in the other comment.

>OK - This makes sense. I have changed `getRecords()` to return a list and the section of code which calls `Chunk.readFrom` and `chunk.getRecords()` is wrapped in a sequence.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 39 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1VpnBERTw3N1BF4cH:-Nd2E3Sp3fHERy5ak2kg:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for properties. See https://developer.android.com/kotlin/style-guide#documentation
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 40 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1WAzZ3lD22LeTNM8Q:-Nd2E41400IgLP1hNDZ5:byuur8x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Any reason why this isn't defined inside the Riegeli object?
</blockquote></details>

No particular reason, moved this item inside the object
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 48 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1W3rFBSWbbGWmikcH:-Nd2E8dE6TWiV7fmTOJv:bf3sn2n) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Any reason why this isn't defined inside the Riegeli object?
</blockquote></details>

No particular reason, moved this item inside the object 
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 69 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XYR31a5uGA9Ky9jv:-Nd2I1wg8QIXRCq1uNHz:bs88jdi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If your function takes in an input stream, the general convention is that the caller (i.e. whatever opens the stream) is responsible for closing it. CountingInputStream.close just delegates to the `close` method of the wrapped input stream.
</blockquote></details>

Gotcha - so `readCompressedFileWithRecords` will implement `file.inputStream().use {}` and in `readCompressedInputStreamWithRecords`, we will not assume responsibility for closing the stream?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 71 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1v6D87V1XNEjHcZ40:-Nd2EtTi9nz1gsdJmAMr:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just to make sure, is it intentional that we're reading this header and then throwing it away? If so, leave a comment so it's clear.
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 78 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1vg1S6K9stYPLAny2:-Nd2HOCp2rXAxe-kxAPv:b3w3iwm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the overload which takes in a lambda. This way the string doesn't even need to be constructed unless the logging configuration includes logs at this level.

I also think that `INFO` might be too coarse a logging level for this code and we should probably use `DEBUG` (`INFO` is the default level for all of our `org.wfanet` code, so anything at that level or higher should be generally useful in production). We can always set the logging level to include these in a specific test if desired.
</blockquote></details>

Neat. There's no debug level available, is fine/finer OK?
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 103 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XqtJ-MkhRf9xK6cJ:-Nd2I-mm8EZiFljomKeb:b37g4ng) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrap this in `use` to guarantee that the stream is closed.
</blockquote></details>

With regards to using an InputStream and outputting a sequence -- I'm getting Stream Closed IOExceptions when, say in the tester, I have something like this:

```
val recordSequence = readCompressedFileWithRecords("example-file")

recordSequence.forEach { /* do something */ }
```

In this example, `readCompressedFileWithRe [...]

2023-08-30 18:26 UTC, SanjayVas requested changes
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 2 unresolved discussions (waiting on @jononon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 69 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XYR31a5uGA9Ky9jv:-Nd6bKyi9iNM6bIh03jY:b-plxeza) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L69)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Gotcha - so `readCompressedFileWithRecords` will implement `file.inputStream().use {}` and in `readCompressedInputStreamWithRecords`, we will not assume responsibility for closing the stream?
</blockquote></details>

See my other comment. Sorry for the churn.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 78 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1vg1S6K9stYPLAny2:-Nd6bVta3f3UJ1a6U0JG:buuler5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L78)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Neat. There's no debug level available, is fine/finer OK?
</blockquote></details>

Yes, I meant [`FINE`](https://docs.oracle.com/javase/8/docs/api/java/util/logging/Level.html#FINE) but `FINER` is also okay. Sorry, I get mixed up on which logging system uses what name.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 103 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XqtJ-MkhRf9xK6cJ:-Nd6c4Kf3Ab9yAA_X_U6:bgnnt35) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L103)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

With regards to using an InputStream and outputting a sequence -- I'm getting Stream Closed IOExceptions when, say in the tester, I have something like this:

```
val recordSequence = readCompressedFileWithRecords("example-file")

recordSequence.forEach { /* do something */ }
```

In this example, `readCompressedFileWithRecords` opens the `inputStream` using `file.inputStream().use {}` but by the time I want to iterate through sequence objects, the stream has already been closed. 

The only way around this I have found is to have `readCompressedFileWithRecords` collect the sequence as a List while it has the InputStream open and return that list. I have `readCompressedInputStreamWithRecords` returning a sequence but the user has to ensure that all usages of the sequence occur within a `inputStream.use {}` block.

Would appreciate your guidance on how to move forward here. I feel like it's not user-friendly or intuitive to have a method, `readCompressedInputStreamWithRecords`, which can be used but only as long as you keep the `InputStream` open.
</blockquote></details>

Ah, sorry for the churn on advice here. I didn't think through the fact that stream cannot be closed until after the sequence has been processed. This means that the consumer of the sequence needs some way to ensure that the stream is closed once the sequence has been consumed.

One way to handle this is to move the `use` calls back into `readCompressedInputStreamWithRecords`, but document that the input stream will be closed when the sequence has been exhausted or on any error in sequence production. This means that if someone is calling the InputStream overload they are still responsible for closing the stream in the case that they choose not to exhaust the sequence.
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 66 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd6eiIn2ZQkEstTa_AK:-Nd6eiIn2ZQkEstTa_AL:b-i65xho) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/14ab06dde3589553f677f14d7c409164afa53c7e/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L66)):*
> ```Kotlin
>    * @return A sequence where each element is a ByteString containing the bytes of a record.
>    */
>   fun readCompressedInputStreamWithRecords(incomingInputStream: InputStream): Sequence<ByteString> {
> ```

nit: I'd recommend having this and the `File` version of the method having the same name such that they are overloads of each other. Maybe `readRecords` (assuming we don't actually need the caller to tell us whether the data is compressed).



_Suggestion:_
```Kotlin
readRecords
```
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 32 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd2-hI1A4tbEXvW6zo8:-Nd6gIb01G2Jsff7MxsK:bmx59fb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L32)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

Done - put inside `companion object`
</blockquote></details>

Same note here that the companion object is conventionally declared at the end of the class rather than the beginning.


<!-- Sent from Reviewable.io -->

2023-08-30 22:40 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 103 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XqtJ-MkhRf9xK6cJ:-Nd7__8-B1VIWjAEJuay:blkmoiz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, sorry for the churn on advice here. I didn't think through the fact that stream cannot be closed until after the sequence has been processed. This means that the consumer of the sequence needs some way to ensure that the stream is closed once the sequence has been consumed.

One way to handle this is to move the `use` calls back into `readCompressedInputStreamWithRecords`, but document that the input stream will be closed when the sequence has been exhausted or on any error in sequence production. This means that if someone is calling the InputStream overload they are still responsible for closing the stream in the case that they choose not to exhaust the sequence.
</blockquote></details>

OK - updated the comment to be 
```
/**
   * Reads and decompresses a Riegeli compressed input stream with records.
   *
   * @param incomingInputStream An input stream which contains data which should be decompressed using Riegeli.
   *                            This input stream will be closed when the sequence has been exhausted or upon any error.
   * @return A sequence where each element is a ByteString containing the bytes of a record.
   */
``` 
___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 66 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd6eiIn2ZQkEstTa_AK:-Nd7ZbIx7XVGuLV2XybO:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/14ab06dde3589553f677f14d7c409164afa53c7e/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I'd recommend having this and the `File` version of the method having the same name such that they are overloads of each other. Maybe `readRecords` (assuming we don't actually need the caller to tell us whether the data is compressed).
</blockquote></details>

Done
___
*[`src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt` line 32 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd2-hI1A4tbEXvW6zo8:-Nd7_kpR9lohB3IyfeaD:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/test/kotlin/org/wfanet/measurement/common/riegeli/RiegeliTest.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same note here that the companion object is conventionally declared at the end of the class rather than the beginning.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-30 22:43 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 103 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XqtJ-MkhRf9xK6cJ:-Nd7asCU6XFiJfW4llD2:blvnt7c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L103)):*
<details><summary><i>Previously, jononon (Jonathan Damico) wrote…</i></summary><blockquote>

OK - updated the comment to be 
```
/**
   * Reads and decompresses a Riegeli compressed input stream with records.
   *
   * @param incomingInputStream An input stream which contains data which should be decompressed using Riegeli.
   *                            This input stream will be closed when the sequence has been exhausted or upon any error.
   * @return A sequence where each element is a ByteString containing the bytes of a record.
   */
```
</blockquote></details>

So to confirm - `readRecords(InputStream)` (renamed from `readCompressedInputStreamWithRecords`) is is now opening and closing the `InputStream` using `.use {}`


<!-- Sent from Reviewable.io -->

2023-08-30 23:14 UTC, SanjayVas approved these changes
> Reviewed 1 of 2 files at r2, 4 of 13 files at r9, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jononon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 103 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XqtJ-MkhRf9xK6cJ:-Nd7bjN5E9ptIeJb_Th7:b7e4tcp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L103)):*
> is now opening and closing the `InputStream`

Close. It's now ensuring the `InputStream` gets closed. Technically the stream is opened on construction of the `InputStream` object.


<!-- Sent from Reviewable.io -->

2023-08-30 23:21 UTC, jononon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jononon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 103 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd1XqtJ-MkhRf9xK6cJ:-Nd7kAD6EQrkDWAnWeev:b-g3qkce) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/74486e18912d54962d8e09f179f126b17def9ecb/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> is now opening and closing the `InputStream`

Close. It's now ensuring the `InputStream` gets closed. Technically the stream is opened on construction of the `InputStream` object.
</blockquote></details>

Ah - gotcha. Comment should still work.


<!-- Sent from Reviewable.io -->

2023-08-31 00:12 UTC, jononon reviewed
Just ran the linter for all modified files, checks now pass using my own gh actions.

I'm happy with this PR assuming all checks pass here.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-:-Nd7vZ1RCXtOCEhTJo34:b-a9pz9y)* status: 14 of 24 files reviewed, all discussions resolved (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-31 00:15 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: 14 of 24 files reviewed, 1 unresolved discussion (waiting on @jononon, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt` line 1 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175#-Nd7wEcf5JGH2_mfXq66:-Nd7wEcg-0r13kOxCSSE:b-7poh9x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/aa27f030499e8fd142f7612584ca0968cdc3aaf8/src/main/kotlin/org/wfanet/measurement/common/riegeli/Riegeli.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

nit: fix copyright year/format



_Code quote:_
```Kotlin
2021
```


<!-- Sent from Reviewable.io -->

2023-08-31 00:16 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r14, 9 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: all files reviewed, 1 unresolved discussion (waiting on @jononon, @kungfucraig, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-31 00:19 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-31 20:41 UTC, kungfucraig approved these changes
> Reviewed 2 of 7 files at r12, 1 of 1 files at r14, 7 of 9 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-31 20:41 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-01 00:10 UTC, jononon commented
Rebased with main

2023-09-01 00:17 UTC, jononon commented
Rebased with main

2023-09-01 00:19 UTC, jononon reviewed
> Reviewed 1 of 2 files at r2, 3 of 15 files at r4, 2 of 8 files at r6, 1 of 4 files at r8, 5 of 18 files at r9, 2 of 7 files at r12, 1 of 1 files at r14, 5 of 14 files at r17, 9 of 9 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-01 00:19 UTC, merged