Pulling out grpc_extra_deps and updating the go_register_toolchains version
world-federation-of-advertisers/common-jvm pull request #189
Opened 2023-04-10 17:38 UTC by bdomen-ggl

In the CMM repo, we want to add a GRPC Gateway for the BFF Reporting API to support the Reporting UI. GRPC Gateway requires to call `go_register_toolchains(version = "1.19.4")`. Or at least trying to change things to support the hardcoded version in the dependency would be difficult. The rest of the file is the same to minimize the risk of breaking anything.

2023-04-10 17:38 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189)
<!-- Reviewable:end -->

2023-04-10 17:50 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @bdomen-ggl)

___
*[`build/grpc_extra_deps.bzl` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189#-NSgHLYK7MZTub3jCBRF:-NSgHLYK7MZTub3jCBRG:bwd5b4s) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/558c4623c071531e61234e0d17aa04befe370581/build/grpc_extra_deps.bzl#L31)):*
> ```Starlark
> load("@upb//bazel:workspace_deps.bzl", "upb_deps")
> 
> def grpc_extra_deps(ignore_version_differences = False):
> ```

nit: maybe add  go_toolchain_version arg with the version we want to use as the default?
___
*[`build/grpc_extra_deps.bzl` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189#-NSgGFRA8KEIv6bUauO0:-NSgGFRB8TJ67RciqvKq:b-z41e9o) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/558c4623c071531e61234e0d17aa04befe370581/build/grpc_extra_deps.bzl#L37)):*
> ```Starlark
>     grpc_deps.bzl. Projects that depend on gRPC as an external repository need
>     to call both grpc_deps and grpc_extra_deps, if they have not already loaded
>     the extra dependencies. For example, they can do the following in their
> ```

I think here we can just reference that this loads extra dependencies for gRPC and mention that it's copied from the gRPC repo with changes for version compatibility. I'd go ahead and file a bug on the gRPC repo and include a TODO here for that.



_Suggestion:_
```Starlark
    """Loads additional gRPC dependencies.
    
    This is copied from https://github.com/grpc/grpc with modifications to address version compatibility issues. It must be run after `grpc_deps`.
    
    TODO(<issue ref>): Remove this once the upstream grpc_extra_deps supports a newer Go toolchain.

    Args:
      ignore_version_differences: Plumbed directly to the invocation of
        apple_rules_dependencies.
    """
```


<!-- Sent from Reviewable.io -->

2023-04-17 21:55 UTC, bdomen-ggl commented
*[`build/grpc_extra_deps.bzl` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189#-NSgHLYK7MZTub3jCBRF:-NTGCrsSBfgcJ5nP0Ms2:b-kg4oj9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/558c4623c071531e61234e0d17aa04befe370581/build/grpc_extra_deps.bzl#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe add  go_toolchain_version arg with the version we want to use as the default?
</blockquote></details>

Added input with a default.


<!-- Sent from Reviewable.io -->

2023-04-17 21:56 UTC, bdomen-ggl commented
*[`build/grpc_extra_deps.bzl` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189#-NSgGFRA8KEIv6bUauO0:-NTGCw7a43wDay3j3e0q:b9oqtpe) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/558c4623c071531e61234e0d17aa04befe370581/build/grpc_extra_deps.bzl#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think here we can just reference that this loads extra dependencies for gRPC and mention that it's copied from the gRPC repo with changes for version compatibility. I'd go ahead and file a bug on the gRPC repo and include a TODO here for that.
</blockquote></details>

Updated comment block


<!-- Sent from Reviewable.io -->

2023-04-17 23:40 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)



<!-- Sent from Reviewable.io -->

2023-04-18 17:30 UTC, Marco-Premier approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @YuhongWang-Amazon)



<!-- Sent from Reviewable.io -->

2023-04-18 18:10 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)



<!-- Sent from Reviewable.io -->

2023-04-18 18:14 UTC, YuhongWang-Amazon approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)



<!-- Sent from Reviewable.io -->

2023-04-18 18:40 UTC, merged