Upgrade Mockito
world-federation-of-advertisers/common-jvm pull request #263
Opened 2024-08-12 18:28 UTC by tristanvuong2021

2024-08-12 18:28 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263)
<!-- Reviewable:end -->

2024-08-12 18:52 UTC, SanjayVas requested changes
Follow Conventional Commits. e.g.

> chore!: Upgrade Mockito to v5
>
> BREAKING CHANGE: Targets Java 11

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263#-:-O46urQk7OeH5KRuK6zN:b-dm57p)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`BUILD.bazel` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263#-O46vatmDm-KH1Oc1-Ug:-O46vatmDm-KH1Oc1-Uh:bb6up65) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e0eb1dfe1ad144c22ffe70ca01d6ffc9d41cf5de/BUILD.bazel#L5)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> 
> define_kt_toolchain(
> ```

Can this be moved to //build/rules_kotlin?


<!-- Sent from Reviewable.io -->

2024-08-12 19:23 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`BUILD.bazel` line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263#-O46vatmDm-KH1Oc1-Ug:-O471zXy0q_ohbwBMCHf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e0eb1dfe1ad144c22ffe70ca01d6ffc9d41cf5de/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can this be moved to //build/rules_kotlin?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-12 19:43 UTC, SanjayVas approved these changes
Note that the first line is the PR title. See https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/3659-kubectl-apply-prune/README.md#kubectl-commands-and-flags

Actually looking at the category descriptions, this would probably be `build` rather than `chore`.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263#-:-O476D_pDv9n-24mQK1C:bbhdnjc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-08-14 02:36 UTC, stevenwarejones approved these changes
> Reviewed 2 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-08-14 16:02 UTC, tristanvuong2021 reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-08-14 16:03 UTC, tristanvuong2021 reviewed
> Reviewed 2 of 5 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-08-14 16:06 UTC, merged