fix: Always use coroutine dispatcher as executor for Spanner.
world-federation-of-advertisers/common-jvm pull request #281
Opened 2024-10-03 18:04 UTC by SanjayVas

The previous behavior involved passing a separate Executor for read-write transactions that was independent of the coroutine context.

2024-10-03 18:04 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)
<!-- Reviewable:end -->

2024-10-07 23:35 UTC, SanjayVas commented
Related to https://github.com/googleapis/java-spanner/issues/2698

2024-10-08 18:12 UTC, stevenwarejones approved these changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-09 18:03 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-11 18:56 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-11 18:59 UTC, SanjayVas commented
Moved to draft while trying to resolve the issue of sessions with active transactions being reused.

2024-10-15 15:33 UTC, stevenwarejones reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-21 12:51 UTC, stevenwarejones requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt` line 362 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281#-O9j6um4B94AshX3yzvh:-O9j6um4B94AshX3yzvi:b-u242s2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35ba0d8bbbf3e80c5934ed069bdff501085732f6/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt#L362)):*
> ```Kotlin
>       return manager
>         .runInTransaction { txn ->
>           txn.readRowUsingIndexAsync(table, index, key, columns.asIterable())
> ```

just call the other `readRowUsingIndex` please


<!-- Sent from Reviewable.io -->

2024-10-21 18:25 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt` line 362 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281#-O9j6um4B94AshX3yzvh:-O9kJxc67Trmeq6nMUjN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35ba0d8bbbf3e80c5934ed069bdff501085732f6/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt#L362)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just call the other `readRowUsingIndex` please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-22 14:30 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/281)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-22 16:34 UTC, merged

2024-10-22 20:35 UTC, SanjayVas commented
This has one additional breaking change that wasn't listed in the PR description: read-write transactions are not allowed to be empty. This means that the transaction work passed to `AsyncDatabaseClient.TransactionRunner.run` must interact with the `AsyncDatabaseClient.TransactionContext` in some way.