Add recordio storage client
world-federation-of-advertisers/common-jvm pull request #285
Opened 2024-10-25 13:06 UTC by Marco-Premier

Closing [#1861](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1861) and added RecordIoStorageClient to common-jvm as per @SanjayVas suggestion.

StorageClient that writes / reads Apache Mesos record io file format and uses `StreamingAead` for encrypting / decrypting operations.

The StorageClient streams an encrypted file and emit each record individually.

2024-10-25 13:06 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)
<!-- Reviewable:end -->

2024-10-25 13:26 UTC, stevenwarejones requested changes
> Reviewed 1 of 6 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OA2ptlOA9JvdsP2WZbf:-OA2ptlOA9JvdsP2WZbg:bfwuofq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b09152bcc922b6039790b58fab106aa7aa006fd4/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt#L1)):*
> ```Kotlin
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

please capitalize the C in the file name `...torageClient.kt`
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OA2pznC9VWSPmJ6yj_c:-OA2pznD5Io_gK1YblXj:b-4pn3kb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b09152bcc922b6039790b58fab106aa7aa006fd4/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt#L44)):*
> ```Kotlin
>  * @param dataKey a base64-encoded symmetric data key
>  */
> class RecordIoStorageClient(
> ```

I was thinking you would have two classes
1. StreamingKmsStorageClient
2. RecordIoStorageClient

Then the RecordIoStorageClient is oblivious to the underlying encryption


<!-- Sent from Reviewable.io -->

2024-10-25 15:30 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OA2ptlOA9JvdsP2WZbf:-OA3IGBv0nOZzHvRtzEA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b09152bcc922b6039790b58fab106aa7aa006fd4/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

please capitalize the C in the file name `...torageClient.kt`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OA2pznC9VWSPmJ6yj_c:-OA3IGsH60boX8U_E7PE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b09152bcc922b6039790b58fab106aa7aa006fd4/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageclient.kt#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was thinking you would have two classes
1. StreamingKmsStorageClient
2. RecordIoStorageClient

Then the RecordIoStorageClient is oblivious to the underlying encryption
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-28 13:08 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAICZUa7Z4OQNzYOcvK:-OAICZUa7Z4OQNzYOcvL:b-2syerf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L34)):*
> ```Kotlin
>  * @param storageClient underlying client for accessing blob/object storage
>  */
> class RecordIoStorageClient(private val storageClient: StorageClient) : StorageClient {
> ```

`MesosRecordIoStorageClient` since this isn't necessarily compatible with other RecordIo formats
___
*[`src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStreamingStorageClientTest.kt` line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIEHCf2DOmjo3JqBlQ:-OAIEHCf2DOmjo3JqBlR:b-ftux6a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStreamingStorageClientTest.kt#L38)):*
> ```Kotlin
> const val TARGET_SIZE = 228
> /** Abstract base class for testing implementations of [StorageClient]. */
> abstract class AbstractStreamingStorageClientTest<T : StorageClient> {
> ```

this is unused. is an abstract streaming storage client test needed?
___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt` line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIDx1D33eZHnAsh9uc:-OAIDx1D33eZHnAsh9ud:bgdq42b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt#L32)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class RecordIoStorageClientTest {
> ```

this should extend the abstractstorageclient test
___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt` line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIDajm5899LAAq7ROL:-OAIDajm5899LAAq7ROM:ba9dhq4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt#L43)):*
> ```Kotlin
>   }
> 
>   @Test
> ```

can you add 
1. a test where you write the raw bytes using a normal storage client and then read it with RecordIOStorageClient successfully?
2. a test where invalid format is previously written and then read when a verified error
___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClientTest.kt` line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIED-j-OdicWyF2q5Q:-OAIED-j-OdicWyF2q5R:bgdq42b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/test/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClientTest.kt#L44)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class StreamingAeadStorageClientTest {
> ```

this should extend the abstractstorageclient test


<!-- Sent from Reviewable.io -->

2024-10-28 19:53 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 6 of 8 files reviewed, 15 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`MODULE.bazel.lock` line 1583 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJWGdg57xQrESnu2bB:-OAJWGdg57xQrESnu2bC:b-7xx9a5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a19a40015204040c5224ec936eace8e2b0703035/MODULE.bazel.lock#L1583)):*
> ```JSON
>         ]
>       }
>     },
> ```

There should be no changes to this file unless MODULE.bazel is also changed
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJWYhs6OqqwMvfEo2O:-OAJWYhs6OqqwMvfEo2P:btfqn5x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel#L9)):*
> ```Starlark
>     srcs = glob(["*.kt"]),
>     deps = [
>         "//imports/java/com/google/cloud/storage",
> ```

This should not depend directly on GCS.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJWsILAoRBnms9VEkr:-OAJWmkI3JanaNvhtBjR:big36lv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.securecomputation.teesdk.cloudstorage.v1alpha
> ```

This doesn't use any Tink primitives and can therefore move under measurement.storage, with the Kotlin package updated to match the Bazel package.



_Suggestion:_
```Kotlin
package org.wfanet.measurement.common.crypto.tink
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJXMtw0tUtL4fUy9lv:-OAJXMtw0tUtL4fUy9lw:b-11f0p7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L47)):*
> ```Kotlin
>   *
>   * @param blobKey The key (or name) of the blob where the content will be stored.
>   * @param content A Flow<ByteString> representing the source of RecordIO rows that will be stored.
> ```

nit: the information that each item in the flow is a single record should go here
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJYGMnE3k_Y08NNRhm:-OAJYGMnE3k_Y08NNRhn:bhbr19z) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L58)):*
> ```Kotlin
>         val rawBytes = byteString.toByteArray()
>         val recordSize = rawBytes.size.toString()
>         val fullRecord = recordSize + "\n" + String(rawBytes, Charsets.UTF_8)
> ```

Extract a RECORD_DELIMITER constant?



_Code quote:_
```Kotlin
"\n"
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 87 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJXcJyE8xHX9u3GtUT:-OAJXcJyE8xHX9u3GtUU:b-ucmdvq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L87)):*
> ```Kotlin
> 
>   /** A blob that will read the content in RecordIO format */
>   private inner class RecordioBlob(private val blob: StorageClient.Blob, private val blobKey: String) :
> ```

nit: Just `Blob` is fine since this is both private and defined in the context of `RecordIoStorageClient`.



_Suggestion:_
```Kotlin
Blob
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJ_CxB0-o_YDCOoPs5:-OAJ_CxB0-o_YDCOoPs6:b-c0so9l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L110)):*
> ```Kotlin
>       val buffer = StringBuilder()
>       var currentRecordSize = -1
>       var recordBuffer = ByteArrayOutputStream()
> ```

Use ByteString.Output to avoid unnecessary copies. It can be reset, so this can be a val



_Suggestion:_
```Kotlin
val recordBuffer = ByteString.newOutput()
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 114 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJZ-8_EyFz2_vPlZLx:-OAJZ-8_EyFz2_vPlZLy:undefined) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L114)):*
> ```Kotlin
>       blob.read().collect { chunk ->
>         var position = 0
>         val chunkString = chunk.toByteArray().toString(Charsets.UTF_8)
> ```





_Suggestion:_
```Kotlin
toStringUtf8()
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJamYI2-8y7fLIKyUj:-OAJamYI2-8y7fLIKyUk:b45h) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.securecomputation.teesdk.cloudstorage.v1alpha
> ```





_Suggestion:_
```Kotlin
package org.wfanet.measurement.
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJajPnBBdEE-iME1Pk:-OAJajPnBBdEE-iME1Pl:bmj0n1p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L28)):*
> ```Kotlin
> import kotlin.coroutines.CoroutineContext
> import kotlinx.coroutines.*
> import kotlinx.coroutines.flow.*
> ```

Wildcard imports are not allowed. See https://developer.android.com/kotlin/style-guide



_Code quote:_
```Kotlin
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJf_o15ymzUJ2gUvv5:-OAJf_o15ymzUJ2gUvv6:b-chplt0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L60)):*
> ```Kotlin
>    */
>   override suspend fun writeBlob(blobKey: String, content: Flow<ByteString>): StorageClient.Blob {
>     val encryptedContent = flow {
> ```

We should be able to copy a lot of the read/write implementation from GcsStorageClient, as that also operates on ReadableByteChannel/WriteableByteChannel. In particular, use the extension functions in src/m [...]

2024-10-28 23:00 UTC, kungfucraig reviewed
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 6 of 8 files reviewed, 16 unresolved discussions (waiting on @dawnwang22 and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJ9g-26deuVssxOOGL:-OAJ9g-26deuVssxOOGM:b3jusdq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L72)):*
> ```Kotlin
> 
>     val wrappedBlob: StorageClient.Blob = storageClient.writeBlob(blobKey, processedContent)
>     logger.fine { "Wrote content to storage with blobKey: $blobKey" }
> ```

Part of me would like to log the number of records written


<!-- Sent from Reviewable.io -->

2024-10-28 23:01 UTC, kungfucraig reviewed
This looks to be shaping up well. I'm going to defer to @SanjayVas and @stevenwarejones at this point. If you need a final approval to unblock when they're done let me know.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-:-OAKM2cS6Zo1n0KIlbcd:b-23bf5b)* status: 6 of 8 files reviewed, 16 unresolved discussions (waiting on @dawnwang22 and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2024-10-29 11:57 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 0 of 11 files reviewed, 14 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClientTest.kt` line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIED-j-OdicWyF2q5Q:-OAMjeTn0aFhqx9gbjTK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/test/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClientTest.kt#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should extend the abstractstorageclient test
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJWYhs6OqqwMvfEo2O:-OAJsG6-35d7TTMSU6Sb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should not depend directly on GCS.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStreamingStorageClientTest.kt` line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIEHCf2DOmjo3JqBlQ:-OAJ7b8Z-KQMFU94L3jS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStreamingStorageClientTest.kt#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this is unused. is an abstract streaming storage client test needed?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt` line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIDx1D33eZHnAsh9uc:-OAJ7dXY5p70uDW0sYVO:b-4wvibr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should extend the abstractstorageclient test
</blockquote></details>

This is slightly different form the KmsStorageClient class, as the generated blob is not a random array of bytes, nor the test for testing the size would work as `writeBlob` method adds the length of each record to the resulting blob.
___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt` line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAIDajm5899LAAq7ROL:-OAJqdEY1uPUpnQPJ9qm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/test/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClientTest.kt#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add 
1. a test where you write the raw bytes using a normal storage client and then read it with RecordIOStorageClient successfully?
2. a test where invalid format is previously written and then read when a verified error
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJWsILAoRBnms9VEkr:-OAMoXd06bNjnG-2rk-C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't use any Tink primitives and can therefore move under measurement.storage, with the Kotlin package updated to match the Bazel package.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAICZUa7Z4OQNzYOcvK:-OAJ7KcZ1F35WKIJyeai:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L34)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`MesosRecordIoStorageClient` since this isn't necessarily compatible with other RecordIo formats
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJYGMnE3k_Y08NNRhm:-OAMpoFOE2XXMKb7OjoS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract a RECORD_DELIMITER constant?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJ9g-26deuVssxOOGL:-OAMscQd0KIpNf0qIYOS:bt433vt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L72)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Part of me would like to log the number of records written
</blockquote></details>

totally agree!
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 110 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJ_CxB0-o_YDCOoPs5:-OAMtXkZ0rdZoygr4G3-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L110)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use ByteString.Output to avoid unnecessary copies. It can be reset, so this can be a val
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 114 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJZ-8_EyFz2_vPlZLx:-OAMtXyM5K-gxT6rIfzx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L114)):*
> ```Kotlin
>       blob.read().collect { chunk ->
>         var position = 0
>         val chunkString = chunk.toByteArray().toString(Charsets.UTF_8)
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJamYI2-8y7fLIKyUj:-OAJs2sv2HQ8bT4NjIfm:b-896fix) ([raw file](https://githu [...]

2024-10-30 08:44 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 0 of 11 files reviewed, 13 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`MODULE.bazel.lock` line 1583 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJWGdg57xQrESnu2bB:-OARZWZ9EE6ELtUNeybc:bjtrao8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a19a40015204040c5224ec936eace8e2b0703035/MODULE.bazel.lock#L1583)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There should be no changes to this file unless MODULE.bazel is also changed
</blockquote></details>

not sure why this pops up. probably a rebase I did, but  I reverted it now
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 63 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAOkF7fEqaWcLF9apdP:-OARZN0RCLNu8MKjpDKo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c86626798c31bd496d8df950f8f17689651ef898/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The whole point of java.nio is to avoid using IO streams for bytes and instead use ByteBuffers so that all reads/writes are buffered. What this means is that you want to have your own WriteableByteChannel implementation that emits flow elements on write rather than wrapping an OutputStream.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAOqVIq1CRFisqptCOB:-OARIMJP8w-TuCM8UO-B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c86626798c31bd496d8df950f8f17689651ef898/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use [`Flow.produceIn`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/produce-in.html) to get the flow elements into a Channel.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAOyLT94GrlZWUL5ddE:-OARDxzU5cBPYW89uXFa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c86626798c31bd496d8df950f8f17689651ef898/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L163)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `ReadableByteChannel.asFlow` extension from `org.wfanet.measurement.common`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 16:11 UTC, stevenwarejones approved these changes
> Reviewed 5 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 6 of 11 files reviewed, 12 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt` line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAJYGMnE3k_Y08NNRhm:-OATAi9q0bAiv4DfXgGg:b5y13ia) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49e080f75a948a9d5af6de2db8d8b4a18d780ac8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/RecordIoStorageClient.kt#L58)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this is fine to extract but the Mesos standard seems to specify the delimiter so I"m fine how it was


<!-- Sent from Reviewable.io -->

2024-10-30 18:17 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 6 of 11 files reviewed, 17 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 69 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATFwSI2DACDXF9yjiG:-OATFwSI2DACDXF9yjiH:b-ptpcgr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L69)):*
> ```Kotlin
>    * @return A Blob object representing the encrypted data that was written to storage.
>    */
>   //  override suspend fun writeBlob(blobKey: String, content: Flow<ByteString>): StorageClient.Blob
> ```

nit: drop commented-out code
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 104 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATVwwQ6aODKd8OtjE8:-OATVwwQ6aODKd8OtjE9:b-b5m326) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L104)):*
> ```Kotlin
>   override suspend fun writeBlob(blobKey: String, content: Flow<ByteString>): StorageClient.Blob {
>     val encryptedContent = channelFlow {
>       val channel = Channel<ByteString>(Channel.UNLIMITED)
> ```

Don't declare another channel. Use the one from the ProducerScope.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 113 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATUSNC4yKiyjc1BY4O:-OATUSNC4yKiyjc1BY4P:btb25pp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L113)):*
> ```Kotlin
>             src.get(bytes)
>             channel.trySend(bytes.toByteString())
>             return bytesWritten
> ```

I think this is doing at least one unnecessary copy. You can copy from a ByteBuffer directly into a ByteString. Finally, you only want to return the number of bytes actually "written", so you need to condition on whether trySend succeeded.



_Suggestion:_
```Kotlin
            val bytes = ByteString.copyFrom(src)
            val result: ChannelResult<Unit> = channel.trySend(bytes)
            if (result.isClosed) {
              throw ClosedChannelException()
            }
            return if (result.isSuccess) { bytes.size() } else { 0 }
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 116 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATVBc_8hBdSVXzgckd:-OATVBc_8hBdSVXzgcke:undefined) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L116)):*
> ```Kotlin
>           }
> 
>           override fun isOpen() = true
> ```





_Suggestion:_
```Kotlin
channel.isClosedForSend
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 125 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATWFvFCc7EOdxvpa9O:-OATWFvFCc7EOdxvpa9P:b-6n70yr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L125)):*
> ```Kotlin
>       launch {
>         for (byteString in channel) {
>           send(byteString)
> ```

See above note about not needing two channels.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 136 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATZj2j26ZXfEEMZbeb:-OATZj2j26ZXfEEMZbec:b-4w4j0x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L136)):*
> ```Kotlin
>       }
> 
>       ciphertextChannel.close()
> ```

Use try-with-resources pattern. In Kotlin, this is the `use` extension.

Note that the suggestion below doesn't handle the other issue, which is that you need to call `write` on the byte channel in a loop until all bytes from the buffer are consumed.



_Suggestion:_
```Kotlin
      streamingAead.newEncryptingChannel(flowEmittingChannel, blobKey.encodeToByteArray()).use { ciphertextChannel ->
         content.collect { byteString ->
           byteString.asReadOnlyByteBufferList().forEach { buffer -> ciphertextChannel.write(buffer) }
         }
      }
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 139 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATb9pW8U9HyGjWAN3A:-OATb9pW8U9HyGjWAN3B:bdvtpnv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L139)):*
> ```Kotlin
>     }
> 
>     val wrappedBlob: StorageClient.Blob = storageClient.writeBlob(blobKey, encryptedContent)
> ```

Something is tickling my brain about this implementation that makes me think it shouldn't work. `collect` will suspend until everything is collected, but it's writing into a non-blocking WriteableByteChannel that itself emits a flow which is then consumed by the `writeBlob` call to the underlying StorageClient. In theory, I would expect `collect` to therefore suspend until `writeBlob` completes.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 191 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATcgQx0Z-2v8XCphRE:-OATcgQy57zlycMZRmus:b-btitku) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L191)):*
> ```Kotlin
>               override fun read(buffer: ByteBuffer): Int {
>                 if (currentChunk == null || bufferOffset >= currentChunk!!.size()) {
>                   currentChunk = runBlocking { chunkChannel.receiveCatching().getOrNull() }
> ```

The ReadableByteChannel should be non-blocking. If it couldn't read anything (i.e. couldn't receive anything from the coroutine channel), the `read` method should return `0`.

Use ReceiveChannel.tryReceive to accomplish this.



_Code quote:_
```Kotlin
currentChunk = runBlocking { chunkChannel.receiveCatching().getOrNull() }
```


<!-- Sent from Reviewable.io -->

2024-10-30 23:04 UTC, stevenwarejones approved these changes
> Reviewed 5 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: all files reviewed, 14 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-31 08:45 UTC, Marco-Premier reviewed
@kungfucraig I think the PR now is ready for final review :)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-:-OAWk24g1gvuwULo9Ixl:bv4hi8q)* status: 10 of 13 files reviewed, 12 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 104 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATVwwQ6aODKd8OtjE8:-OAWRaITEQ4wREcjrBqr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't declare another channel. Use the one from the ProducerScope.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 113 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATUSNC4yKiyjc1BY4O:-OAWS6Rc1tmfRR-3YvsL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this is doing at least one unnecessary copy. You can copy from a ByteBuffer directly into a ByteString. Finally, you only want to return the number of bytes actually "written", so you need to condition on whether trySend succeeded.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 116 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATVBc_8hBdSVXzgckd:-OAWSuwL53PQs_6ORiF7:b-1d9kdt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L116)):*
> ```Kotlin
>           }
> 
>           override fun isOpen() = true
> ```

I think this is `!channel.isClosedForSend`
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 125 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATWFvFCc7EOdxvpa9O:-OAWSyim2PrjtNTnbCSF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See above note about not needing two channels.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 136 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATZj2j26ZXfEEMZbeb:-OAWTXWb6lErweInUe8k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use try-with-resources pattern. In Kotlin, this is the `use` extension.

Note that the suggestion below doesn't handle the other issue, which is that you need to call `write` on the byte channel in a loop until all bytes from the buffer are consumed.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 191 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OATcgQx0Z-2v8XCphRE:-OAWZhgR47ORObwZhh40:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f916d59d3d0e99233ee3d4221b8abf24bc3fba5b/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The ReadableByteChannel should be non-blocking. If it couldn't read anything (i.e. couldn't receive anything from the coroutine channel), the `read` method should return `0`.

Use ReceiveChannel.tryReceive to accomplish this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-31 17:26 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: all files reviewed, 18 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_K9MDF-TNfgL9rfA:-OAY_K9MDF-TNfgL9rfB:b-otyb65) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L29)):*
> ```Kotlin
>  * @property delegate The [ReceiveChannel] from which this [ReadableByteChannel] will read data.
>  * @return The number of bytes read into the buffer, or -1 if the channel is closed and no data
>  *   remains.
> ```

This is misplaced.



_Code quote:_
```Kotlin
 * @return The number of bytes read into the buffer, or -1 if the channel is closed and no data
 *   remains.
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 37 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYY5fzBm7h88REAH7Z:-OAYY5fzBm7h88REAH7_:b3czn6b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L37)):*
> ```Kotlin
>   override fun read(destination: ByteBuffer): Int {
>     val result = delegate.tryReceive()
>     val byteString = result.getOrNull() ?: return -1 // -1 indicates the end of the stream
> ```

Getting no result does not mean that there is no more data, it just means there's no data available *yet*. You need to handle failed and closed separately. See https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-receive-channel/try-receive.html and https://docs.oracle.com/javase/8/docs/api/index.html?java/nio/ByteBuffer.html
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYZLX6EEXdo_7P8ZMo:-OAYY_-BDPAufHp6bi-S:b-gafapu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L38)):*
> ```Kotlin
>     val result = delegate.tryReceive()
>     val byteString = result.getOrNull() ?: return -1 // -1 indicates the end of the stream
>     destination.put(byteString.toByteArray())
> ```

The buffer may have less remaining space than the size of the ByteString. You need to check whether there is enough space first to avoid a `BufferOverflowException`, and then only write however many bytes there is space for. Finally, you need to only return however many bytes were written.

This means you'll need to internally buffer the bytes from the delegate channel that couldn't be written to the destination buffer, and only read from the channel once that internal buffer is empty.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYZoARAGI2CCFxn_ia:-OAYZoARAGI2CCFxn_ib:b82fkh2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L38)):*
> ```Kotlin
>     val result = delegate.tryReceive()
>     val byteString = result.getOrNull() ?: return -1 // -1 indicates the end of the stream
>     destination.put(byteString.toByteArray())
> ```

This does an additional copy to a ByteArray before copying into the destination buffer. Use ['ByteString.copyTo'](https://protobuf.dev/reference/java/api-docs/com/google/protobuf/ByteString.html#copyTo-java.nio.ByteBuffer-) instead, calling `substring` first if necessary.



_Code quote:_
```Kotlin
toByteArray()
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_ANCD0X4bRQvkFun:-OAY_ANCD0X4bRQvkFuo:undefined) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L45)):*
> ```Kotlin
> 
>   override fun close() {
>     delegate.cancel()
> ```





_Suggestion:_
```Kotlin
close()
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_eET6A_2jRJqDlMP:-OAY_eET6A_2jRJqDlMQ:b-otyb65) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt#L31)):*
> ```Kotlin
>  * @constructor Creates a writable channel that writes each [ByteBuffer] as a [ByteString] to the
>  *   provided [SendChannel].
>  * @throws ClosedChannelException if the channel is closed and cannot accept more data.
> ```

This is misplaced.



_Code quote:_
```Kotlin
 * @throws ClosedChannelException if the channel is closed and cannot accept more data.
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_SEP4BnoZNDXeM1v:-OAY_SEP4BnoZNDXeM1w:b7hqygb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt#L36)):*
> ```Kotlin
>   WritableByteChannel {
>   override fun write(source: ByteBuffer): Int {
>     val byteString = ByteString.copyFrom(source)
> ```

Similar notes as above for the readable version. You need to handle the case where the channel is not ready to receive, but isn't yet closed. In this case, you need to return that 0 bytes were written and not consume any bytes from the buffer.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYadYF4CF-hVhOwNsT:-OAYadYF4CF-hVhOwNsU:bxsfitz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L69)):*
> ```Kotlin
>   override suspend fun writeBlob(blobKey: String, content: Flow<ByteString>): StorageClient.Blob {
>     val encryptedContent = channelFlow {
>       val channel = this@channelFlow
> ```

I don't think this line is necessary. You're copying a variable into a scope that can already access it with the same name.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 76 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYb-D7EGhYgz0ep-m1:-OAYb-D7EGhYgz0ep-m2:b-u65gio) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L76)):*
> ```Kotlin
>         content.collect { byteString ->
>           byteString.asReadOnlyByteBufferList().forEach { buffer ->
>             ciphertextChannel.write(buffer)
> ```

You need to handle the case where the channel returns that fewer than buffer.remaining bytes were written.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 12 [...]

2024-10-31 23:30 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: all files reviewed, 19 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 33 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAZu6Sq-LS9mCVRs3yT:-OAZu6Sq-LS9mCVRs3yU:b-uc6c43) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L33)):*
> ```Kotlin
>  *   [ReceiveChannel] and writes it to the specified [ByteBuffer].
>  */
> class CoroutineReadableByteChannel(private val delegate: ReceiveChannel<ByteString>) :
> ```

These classes warrant their own unit tests. You can use unbuffered (rendezvous) channels to trigger some of the more interesting behavior w.r.t. not being ready for send/receive.


<!-- Sent from Reviewable.io -->

2024-11-04 12:28 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 10 of 16 files reviewed, 19 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 29 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_K9MDF-TNfgL9rfA:-OAqWouwBJjzxnpJovfx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is misplaced.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 33 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAZu6Sq-LS9mCVRs3yT:-OAr3p-hBo3rjz0y53u4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These classes warrant their own unit tests. You can use unbuffered (rendezvous) channels to trigger some of the more interesting behavior w.r.t. not being ready for send/receive.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 37 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYY5fzBm7h88REAH7Z:-OAqbQHEBv790C1VhVMy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Getting no result does not mean that there is no more data, it just means there's no data available *yet*. You need to handle failed and closed separately. See https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-receive-channel/try-receive.html and https://docs.oracle.com/javase/8/docs/api/index.html?java/nio/ByteBuffer.html
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYZLX6EEXdo_7P8ZMo:-OAqf_Lv2yx25PZv00P4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The buffer may have less remaining space than the size of the ByteString. You need to check whether there is enough space first to avoid a `BufferOverflowException`, and then only write however many bytes there is space for. Finally, you need to only return however many bytes were written.

This means you'll need to internally buffer the bytes from the delegate channel that couldn't be written to the destination buffer, and only read from the channel once that internal buffer is empty.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYZoARAGI2CCFxn_ia:-OAqkLnSEqKJBKsLJ4sa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This does an additional copy to a ByteArray before copying into the destination buffer. Use ['ByteString.copyTo'](https://protobuf.dev/reference/java/api-docs/com/google/protobuf/ByteString.html#copyTo-java.nio.ByteBuffer-) instead, calling `substring` first if necessary.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_ANCD0X4bRQvkFun:-OAqkXqn8nKcbDelk94z:b-vqmrj7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L45)):*
> ```Kotlin
> 
>   override fun close() {
>     delegate.cancel()
> ```

I don't see `close` method available?
The `cancel` method does close the channel: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-receive-channel/#-2081943076%2FFunctions%2F1975948010
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_eET6A_2jRJqDlMP:-OAqo7Vh1DiS1gtxk9vM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is misplaced.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_SEP4BnoZNDXeM1v:-OAqo9byD6ylU36hqnUA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Similar notes as above for the readable version. You need to handle the case where the channel is not ready to receive, but isn't yet closed. In this case, you need to return that 0 bytes were written and not consume any bytes from the buffer.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYadYF4CF-hVhOwNsT:-OAr5vM6AnnGzM_YkTjK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this line is necessary. You're copying a variable into a scope that can already access it with the same name.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 76 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAYb-D7EGhYgz0ep-m1:-OAr8JP69LVvULcgKno2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You need to handle the case where the channel returns that fewer than buffer.remaining bytes were written.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 124 at r [...]

2024-11-04 20:47 UTC, SanjayVas requested changes
> Reviewed 2 of 11 files at r4, 4 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 14 of 16 files reviewed, 15 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAY_ANCD0X4bRQvkFun:-OAsj0X2Cn51dwx-KeDq:b-6yatpz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a19e32588d43a91a9a4173b1c4f4baec58eca3e/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L45)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I don't see `close` method available?
The `cancel` method does close the channel: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-receive-channel/#-2081943076%2FFunctions%2F1975948010
</blockquote></details>

Sorry, I was looking at SendChannel.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 35 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAshMzN7jlJscqGwH-Q:-OAshMzN7jlJscqGwH-R:b-lpztvf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L35)):*
> ```Kotlin
> 
>   private var remainingBytes: ByteArray? = null
>   private var remainingOffset = 0
> ```

Use a ByteBuffer, which would also mean you shouldn't need to track the offset yourself and you can possibly avoid an extra copy by using `ByteString.asReadOnlyByteBuffer`.



_Code quote:_
```Kotlin
  private var remainingBytes: ByteArray? = null
  private var remainingOffset = 0
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 53 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAsh0Gs7lO0zJoiREPf:-OAsh0Gs7lO0zJoiREPg:bn1qebg) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L53)):*
> ```Kotlin
>    */
>   override fun read(destination: ByteBuffer): Int {
>     remainingBytes?.let {
> ```

nit: prefer standard if structure, especially if not using the result of `let`.



_Suggestion:_
```Kotlin
if (remainingBytes != null) {
```
___
*[`src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt` line 34 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAssC5ICWinllqalV4m:-OAssC5J8Tz6PlTW_iyv:b-pumem8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt#L34)):*
> ```Kotlin
> 
>   private lateinit var channel: Channel<ByteString>
>   private lateinit var coroutineReadableByteChannel: CoroutineReadableByteChannel
> ```

If you're just calling the constructors, you can make the properties not be lateinit and instead just call these during regular instance initialization. Recall that JUnit will initialize a new instance for each test method.

That said, you may want to initialize these within each test method to have more control or be able to use builders like `produce`.



_Suggestion:_
```Kotlin
  private val channel: Channel<ByteString> = Channel()
  private val coroutineReadableByteChannel = CoroutineReadableByteChannel(channel)
```
___
*[`src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt` line 52 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAssPnSE7uzr5u1tUks:-OAssPnT8pW5uD47AlCa:bgi0eqx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt#L52)):*
> ```Kotlin
>     val buffer = ByteBuffer.allocate(5)
>     launch { channel.send(testData) }
>     delay(100)
> ```

Unit tests should neither use real delays nor rely on timing.
___
*[`src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt` line 59 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAsv74S4jPHn2zqDrGT:-OAsv74S4jPHn2zqDrGU:bm6gezt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt#L59)):*
> ```Kotlin
> 
>   @Test
>   fun `read - handles remaining bytes correctly`() = runBlocking {
> ```

nit: be more specific than "handles correctly"



_Suggestion:_
```Kotlin
read buffers channel items when destination buffer is filled
```
___
*[`src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt` line 65 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAsuGSDE-HXQgGwzxeO:-OAsuGSDE-HXQgGwzxeP:b-hp6t2l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/test/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannelTest.kt#L65)):*
> ```Kotlin
>     delay(100)
>     val bytesRead = coroutineReadableByteChannel.read(buffer)
>     assertThat(5).isEqualTo(bytesRead)
> ```

These test assertions are inverted. In Truth, you wrap the Subject around the actual value. See https://truth.dev/faq#order
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt` line 140 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAsmkJf4RZDqkecORki:-OAsmkJf4RZDqkecORkj:b-i2hx0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt#L140)):*
> ```Kotlin
> 
>   companion object {
>     internal val logger = Logger.getLogger(this::class.java.name)
> ```

Can this be private?



_Code quote:_
```Kotlin
internal
```
___
*[`src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt` line 54 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAspk333baM93A1wloq:-OAspk333baM93A1wlor:b-t4rc50) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt#L54)):*
> ```Kotlin
>     var recordsWritten = 0
>     val processedContent = flow {
>       val outputStream = ByteArrayOutputStream()
> ```

Use ByteString.Output so you never need to call ByteString.copyFrom. ByteString.Output extends OutputStream.



_Suggestion:_
```Kotlin
val outputStream: ByteString.Output = ByteString.newOutput()
```
___
*[`src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt` line 58 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAsn7JK1mG-CXCJmdvz:-OAsn7JLAtYMb9w7941C:b-vv019k) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/436813abbda026e8dc0130a2e747af55794b3134/src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt#L58)):*
> ```Kotlin
>         val rawBytes = byteString.toByteArray()
>         val recordSize = rawBytes.size.toString()
>         val fullRecord = recordSize + RECORD_DELIMITER + String(rawBytes, Charsets.UTF_8)
> ```

I don't think you ever need `rawBytes`.

In general, you want to avoid copying ByteString into a new ByteArray whenever possible. This is what `toByteArray` does.



_Suggestio [...]

2024-11-05 18:03 UTC, SanjayVas requested changes
> Reviewed 8 of 11 files at r4, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: all files reviewed, 5 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxJdG65ZxMl78fTs4Z:-OAxJdG65ZxMl78fTs4_:b-pcf9eu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L21)):*
> ```Kotlin
> import java.nio.ByteBuffer
> import java.nio.channels.ReadableByteChannel
> import java.util.*
> ```

Wildcard imports are forbidden
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 55 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxJtxB5767Hw3FNaA2:-OAxJtxB5767Hw3FNaA3:b-i5w0dw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L55)):*
> ```Kotlin
>   override fun read(destination: ByteBuffer): Int {
> 
>     if (remainingBuffer != null) {
> ```

You can rewrite this to take advantage of smart casts by assigning `remainingBuffer` to a local variable first. Then you won't need to use the non-null assertion.

Alternatively, I think the better approach would be to have it so that `remainingBuffer` is never null by initializing it to `ByteString.EMPTY.asReadOnlyByteBuffer()` and always assigning it to the ByteString buffer from the coroutine channel. This way you can just check if it has any bytes remaining.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 75 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxN8C_BVPLEEuSJCjg:-OAxN8CaEi_JcSKLLFIO:b5nel5n) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L75)):*
> ```Kotlin
>   }
> 
>   private fun writeToDestination(destination: ByteBuffer, source: ByteBuffer): Int{
> ```

nit: Document what this method is doing, since it's not obvious from the name.

I know that this is essentially `ReadableByteChannel.read`, but with the source ByteBuffer acting as the ByteChannel itself.
___
*[`src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt` line 32 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxRIMd3HxLRsZfsp1v:-OAxRIMd3HxLRsZfsp1w:b-cx3gsr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt#L32)):*
> ```Kotlin
>  * @param storageClient underlying client for accessing blob/object storage
>  */
> class MesosRecordIoStorageClient(private val storageClient: StorageClient) : StorageClient {
> ```

Sorry for not catching this sooner, but you probably want the StorageClient impl to be a private implementation detail class inside of your public `MesosRecordIoStore`, where the latter provides a  similar interface but with the actual record type specified. The class would then abstract away the protobuf message serialization.

Since this PR is already long-lived, I don't mind if that work is done in a follow-up PR.

e.g.

```kotlin
class MesosRecordIoStore<T : Message>(storageClient: StorageClient) {
  private val internalStorageClient = InternalStorageClient(storageClient)

  suspend fun writeBlob(blobKey: String, records: Flow<T>}: Blob

  class Blob {
    fun read(): Flow<T>

    suspend fun delete()
  }

  private class InternalStorageClient(private val storageClient: StorageClient) : StorageClient {
    // The implementation you have now
  }
}
```



_Code quote:_
```Kotlin
StorageClient
```


<!-- Sent from Reviewable.io -->

2024-11-06 09:06 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxJdG65ZxMl78fTs4Z:-OB-dlbf19vm08TZMEhZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wildcard imports are forbidden
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt` line 55 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxJtxB5767Hw3FNaA2:-OB-fchYAXq3yZH-pSBD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can rewrite this to take advantage of smart casts by assigning `remainingBuffer` to a local variable first. Then you won't need to use the non-null assertion.

Alternatively, I think the better approach would be to have it so that `remainingBuffer` is never null by initializing it to `ByteString.EMPTY.asReadOnlyByteBuffer()` and always assigning it to the ByteString buffer from the coroutine channel. This way you can just check if it has any bytes remaining.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt` line 32 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285#-OAxRIMd3HxLRsZfsp1v:-OB-h9ju0YRarOdYjiCu:bqzsecj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d6bab808c54b3d10ae6af4503a518a6e9129f9e8/src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry for not catching this sooner, but you probably want the StorageClient impl to be a private implementation detail class inside of your public `MesosRecordIoStore`, where the latter provides a  similar interface but with the actual record type specified. The class would then abstract away the protobuf message serialization.

Since this PR is already long-lived, I don't mind if that work is done in a follow-up PR.

e.g.

```kotlin
class MesosRecordIoStore<T : Message>(storageClient: StorageClient) {
  private val internalStorageClient = InternalStorageClient(storageClient)

  suspend fun writeBlob(blobKey: String, records: Flow<T>}: Blob

  class Blob {
    fun read(): Flow<T>

    suspend fun delete()
  }

  private class InternalStorageClient(private val storageClient: StorageClient) : StorageClient {
    // The implementation you have now
  }
}
```
</blockquote></details>

Yes please as I'd like to merge this PR and mark some progress.
I added a TODO for it.


<!-- Sent from Reviewable.io -->

2024-11-06 18:20 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dawnwang22 and @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-11-06 18:52 UTC, Marco-Premier reviewed
> Reviewed 9 of 11 files at r4, 1 of 6 files at r7, 3 of 5 files at r8, 1 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dawnwang22 and @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-11-06 18:52 UTC, merged