Added RabbitMqClient to common-jvm
world-federation-of-advertisers/common-jvm pull request #286
Opened 2024-10-28 17:14 UTC by Marco-Premier

Closing [this pr](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1873) in favor of this new one in `common-jvm` as per @SanjayVas suggestion.

`RabbitMqClient` will not launch a new process for messages coming from RabbitMQ, but rather invoke the abstract method `runWork`. Concrete classes will have to provide implementation for this method.

- RabbitMqClient is ControlPlane agnostic now.
- Can work for single or multiple messages.
- For `Single Message` it'll exit the execution once the Message coming from RabbitMQ queue has been process allowing for re-provisioning the VM.

2024-10-28 18:50 UTC, SanjayVas requested changes
Follow Conventional Commits for PR descriptions as described in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-:-OAJPRKs7dkYt43FTIW6:b-6reqqs)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`imports/java/rabbitmq/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAJPgw39Y812RRmq8al:-OAJPgw39Y812RRmq8am:bjphwvy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/imports/java/rabbitmq/BUILD.bazel#L1)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> ```

The Bazel path under imports should match the JVM package. This should therefore be at `//imports/java/com/rabbitmq/client`
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAJPy44A0Pb3AuUjkHA:-OAJPy44A0Pb3AuUjkHB:b-6fgf6n) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L41)):*
> ```Kotlin
>  * @property rabbitMqFlags Configuration parameters for RabbitMQ connection and behavior
>  */
> @CommandLine.Command(
> ```

This client should just be a concrete Kotlin class, not a whole command-line application. e.g.

```kotlin
class RabbitMqClient(host: String, port: String, username: String, password: String) : Autocloseable {
  fun <T> subscribe(queueName: String): ReceiveChannel<QueueMessage<T>> {
    // Init connection if not yet initialized.
    // Return Kotlin channel where channel being closed is equivalent to unsubscribing
  }

  override fun close() {
    // Close the connection
  }

  class QueueMessage<T> {
    val body: T
    
    fun ack() {
    }

    fun nack() {
    }
  }
}
```


<!-- Sent from Reviewable.io -->

2024-10-28 23:09 UTC, kungfucraig requested changes
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAKMztd5mc49WRqAh5a:-OAKMztd5mc49WRqAh5b:b-t5msas) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
> ```Kotlin
>   showDefaultValues = true
> )
> abstract class RabbitMQClient : Runnable {
> ```

I don't think we want this to be an abstract class, rather one that can be instantiated and used by whatever client. 

Maybe provide a "getWork" method that returns a very light weight WorkItem object and have the WorkItem provide ack and nack methods?

I think that would also allow for multi-threaded processing, whereas the current implementation won't. I know this isn't a requirement, but just saying that the way I outlined above is more flexible.

@stevenwarejones @SanjayVas Wdyt?


<!-- Sent from Reviewable.io -->

2024-10-29 16:41 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAJPy44A0Pb3AuUjkHA:-OAO5tXC4s5duHgqJrHm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This client should just be a concrete Kotlin class, not a whole command-line application. e.g.

```kotlin
class RabbitMqClient(host: String, port: String, username: String, password: String) : Autocloseable {
  fun <T> subscribe(queueName: String): ReceiveChannel<QueueMessage<T>> {
    // Init connection if not yet initialized.
    // Return Kotlin channel where channel being closed is equivalent to unsubscribing
  }

  override fun close() {
    // Close the connection
  }

  class QueueMessage<T> {
    val body: T
    
    fun ack() {
    }

    fun nack() {
    }
  }
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAKMztd5mc49WRqAh5a:-OAO5ypfDX0tri6W6rJQ:bi9yen9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think we want this to be an abstract class, rather one that can be instantiated and used by whatever client. 

Maybe provide a "getWork" method that returns a very light weight WorkItem object and have the WorkItem provide ack and nack methods?

I think that would also allow for multi-threaded processing, whereas the current implementation won't. I know this isn't a requirement, but just saying that the way I outlined above is more flexible.

@stevenwarejones @SanjayVas Wdyt?
</blockquote></details>

The `subscribe` method now sends messages as soon as the receiver acknowledges the previous one. This allows for processing multiple messages at the receiver's own pace by simply calling `ack()` immediately upon receiving each message.
___
*[`imports/java/rabbitmq/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAJPgw39Y812RRmq8al:-OANAYwR7cUfHiYX52h8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/imports/java/rabbitmq/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Bazel path under imports should match the JVM package. This should therefore be at `//imports/java/com/rabbitmq/client`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-29 19:18 UTC, SanjayVas requested changes
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAObzbn0Al-oHMh8Ktm:-OAObzbn0Al-oHMh8Ktn:b32v6bc) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L48)):*
> ```Kotlin
>   private val username: String,
>   private val password: String,
>   private val queueName: String,
> ```

I believe the underlying library supports multiple queue subscriptions per connection, so our code should too. This parameter should be moved to `subscribe` with the expectation that the method may be called multiple times for multiple queues.



_Code quote:_
```Kotlin
  private val queueName: String,
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAOc_U91GOuHXbU4mX_:-OAOc_UA79eBfhj0WgKl:bq6cdva) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L56)):*
> ```Kotlin
> 
>   companion object {
>     private val connections = ConcurrentHashMap<ConnectionKey, ConnectionInfo>()
> ```

This is unnecessarily complex. Just have each instance manage its own connection. It's up to the caller to avoid duplicate connections by reusing the same instance for multiple subscriptions.

You can just use a private `lateinit var` or a `Lazy` to manage the connection for the instance. The latter will even take care of the synchronization for you. e.g.

```kotlin
private val lazyConnection: Lazy<Connection> = lazy {
  // Initialize connection
}

override fun close() {
  if (lazyConnection.isInitialized()) {
    lazyConnection.value.close()
  }
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAOeeb22Fv1TG1cwcXT:-OAOeeb22Fv1TG1cwcXU:boetl7u) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L152)):*
> ```Kotlin
>               channel = rabbitChannel,
>             )
>           runBlocking { forwardChannel.send(message) }
> ```

`runBlocking` should not be used aside from tests or `main`. You want to do this inside of a producer scope instead. This means that the instance needs to manage a `CoroutineScope` using `blockingContext`

```kotlin
private val deliveryScope = CoroutineScope(blockingContext)

fun <T> subscribe(queueName: String): ReceiveChannel<QueueMessage<T>> = deliveryScope.produce {
  // Utilize the lamba receiver's `channel` property
}

override fun close() {
  deliveryScope.cancel()
  // Clean up other resources
}
```


<!-- Sent from Reviewable.io -->

2024-10-29 20:04 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAOeeb22Fv1TG1cwcXT:-OAOrdpM5VexK5CGtCBe:b-mkcw1b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L152)):*
> `runBlocking` should not be used aside from tests or `main`.

This is a case where you may indeed need to interface with blocking code. Using `produce` would still be correct (and also note that `subscribe` should not be a suspend function). You can use `SendChannel.trySendBlocking` rather than `runBlocking`.


<!-- Sent from Reviewable.io -->

2024-10-29 21:22 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAKMztd5mc49WRqAh5a:-OAP8eSy1JCTUDbY0hL8:b-7xaer8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

The `subscribe` method now sends messages as soon as the receiver acknowledges the previous one. This allows for processing multiple messages at the receiver's own pace by simply calling `ack()` immediately upon receiving each message.
</blockquote></details>

The multithreading case was just an example. The point about using inheritance as the mechanism for using this functionality is what I'm objecting to. A client inheriting this functionality breaks separation of concerns.


<!-- Sent from Reviewable.io -->

2024-10-30 10:48 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @dawnwang22, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAKMztd5mc49WRqAh5a:-OAS1AJv81elpb9_cXX6:b6k88ll) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/073fe1dad784103c7c0d70fd1a4e2b27dd42ccca/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The multithreading case was just an example. The point about using inheritance as the mechanism for using this functionality is what I'm objecting to. A client inheriting this functionality breaks separation of concerns.
</blockquote></details>

thanks for it :) I totally agree with this point
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAObzbn0Al-oHMh8Ktm:-OARwRG8ErFtf1T4miE-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe the underlying library supports multiple queue subscriptions per connection, so our code should too. This parameter should be moved to `subscribe` with the expectation that the method may be called multiple times for multiple queues.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAOc_U91GOuHXbU4mX_:-OARwPnX1D0NjvDvK3gi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is unnecessarily complex. Just have each instance manage its own connection. It's up to the caller to avoid duplicate connections by reusing the same instance for multiple subscriptions.

You can just use a private `lateinit var` or a `Lazy` to manage the connection for the instance. The latter will even take care of the synchronization for you. e.g.

```kotlin
private val lazyConnection: Lazy<Connection> = lazy {
  // Initialize connection
}

override fun close() {
  if (lazyConnection.isInitialized()) {
    lazyConnection.value.close()
  }
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAOeeb22Fv1TG1cwcXT:-OARyzvwCrOD7xigX2-R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7a636c7b1c3fc4b3dc23dfc4478848b8ab070095/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> `runBlocking` should not be used aside from tests or `main`.

This is a case where you may indeed need to interface with blocking code. Using `produce` would still be correct (and also note that `subscribe` should not be a suspend function). You can use `SendChannel.trySendBlocking` rather than `runBlocking`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 16:21 UTC, stevenwarejones approved these changes
> Reviewed 5 of 7 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @dawnwang22 and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-10-30 16:28 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 53 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAT9aWV5qnx0N0iO_Bq:-OAT9aWV5qnx0N0iO_Br:b-fg2sca) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L53)):*
> ```Kotlin
> ) : AutoCloseable {
> 
>   private val activeChannels = ConcurrentHashMap<String, Channel>()
> ```

I don't think you need to maintain a collection of active channels. IIUC, you just need to have the coroutine channel and the RabbitMQ channel have cooperative closing. This means adding an `awaitClose` handler to the coroutine channel producer to close the RabbitMQ channel, and a call to `SendChannel.close` from the shutdown listener on the RabbitMQ channel.

When this client instance is closed, we clean everything up by closing the underlying connection and the producing coroutine scope.

Please correct me if my understanding is incorrect.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OATBakqD0rra-6jvgzu:-OATBakrAhCxpytoL4t1:bkfhdum) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L75)):*
> ```Kotlin
>   }
> 
>   private val rabbitMqChannel: Lazy<Channel> = lazy {
> ```

There's multiple channels, so I don't think this property makes sense.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 86 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OATEvcs3dASaSTeF5B8:-OATEvcs3dASaSTeF5B9:b-jsx3fh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L86)):*
> ```Kotlin
>     val body: T,
>     private val deliveryTag: Long,
>     private val channel: Channel?,
> ```

Why would this ever be null?



_Code quote:_
```Kotlin
Channel?
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OATB1XL0-fxiIHqL34z:-OATB1XL0-fxiIHqL35-:b-1req21) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L103)):*
> ```Kotlin
>    * @return A ReceiveChannel that will receive QueueMessages
>    */
>   @kotlinx.coroutines.ExperimentalCoroutinesApi
> ```

This isn't implementing part of the experimental coroutines API, but rather opting-in to use it. It's also a good idea to document what we're using.



_Suggestion:_
```Kotlin
@OptIn(ExperimentalCoroutinesApi::class) // For `produce`.
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 129 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAT916LAsws9O3f8ban:-OAT916LAsws9O3f8bao:bl0vd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L129)):*
> ```Kotlin
>               QueueMessage(body = body as T, deliveryTag = envelope.deliveryTag, channel = channel)
>             this@produce.trySendBlocking(message).onFailure { e ->
>               println("Failed to send message: ${e?.message}")
> ```

Do not print to stdout directly. Use a Logger instance.


<!-- Sent from Reviewable.io -->

2024-10-30 17:58 UTC, kungfucraig approved these changes
> Reviewed 2 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 7 unresolved discussions (waiting on @dawnwang22, @Marco-Premier, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-10-30 18:04 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 53 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAT9aWV5qnx0N0iO_Bq:-OAT_5cZBwDleK1TgXPC:b-e9geog) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you need to maintain a collection of active channels. IIUC, you just need to have the coroutine channel and the RabbitMQ channel have cooperative closing. This means adding an `awaitClose` handler to the coroutine channel producer to close the RabbitMQ channel, and a call to `SendChannel.close` from the shutdown listener on the RabbitMQ channel.

When this client instance is closed, we clean everything up by closing the underlying connection and the producing coroutine scope.

Please correct me if my understanding is incorrect.
</blockquote></details>

`When this client instance is closed, we clean everything up by closing the underlying connection and the producing coroutine scope` yes this is the goal of the `close` method.

I removed the map to hold the rabbitmq channels, and now channels are created directly inside the `subscribe` method.

So the `shutdown listener` is now used to close the coroutine channel. This is it, the coroutine channel is closed if the rabbitmq channel is closed due to "connection failures, error occurs etc).

The `awaitClose` on the other hand closes the rabbitmq channel and save resources if the consumer stop collecting etc
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 75 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OATBakqD0rra-6jvgzu:-OATUgh13OdzbWNKwhu_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's multiple channels, so I don't think this property makes sense.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 86 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OATEvcs3dASaSTeF5B8:-OATUiVU-0ETOG88XGeU:b-tn5n2p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why would this ever be null?
</blockquote></details>

I was testing, that's a typo.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OATB1XL0-fxiIHqL34z:-OATVSuC9xuWPaj_vFyy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't implementing part of the experimental coroutines API, but rather opting-in to use it. It's also a good idea to document what we're using.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 129 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAT916LAsws9O3f8ban:-OATWIsTDR8vSy8kXKVM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ac34a3eabc9c7ff3880a2ff943e5bdb86aebf36c/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do not print to stdout directly. Use a Logger instance.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 23:02 UTC, stevenwarejones reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 3 unresolved discussions (waiting on @dawnwang22 and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU4MSj1DpuQJVjjx-e:-OAUeKyTErhcDWsCnMcG:b-gaz7wm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FYI I just found out that RabbitMQ [has a Reactor-based client](https://github.com/reactor/reactor-rabbitmq) in addition to their regular Java client. That should generally be cleaner to adapt to Kotlin coroutines, given the helpers in kotlinx.coroutines.reactor. For example, the queue Receiver returns a Flux which is convertible to a Kotlin Flow.
</blockquote></details>

reactor-rabbitmq's last release is 1.5 years old. The java client has a more recent release.


<!-- Sent from Reviewable.io -->

2024-10-30 23:14 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 3 unresolved discussions (waiting on @dawnwang22 and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU4MSj1DpuQJVjjx-e:-OAUh6Jm9Fz2G-umJGWe:b717v9s) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

reactor-rabbitmq's last release is 1.5 years old. The java client has a more recent release.
</blockquote></details>

Depending on something outside of the core Rabbit MQ, especially where there is evidence it's not being maintained, is best avoided.


<!-- Sent from Reviewable.io -->

2024-10-30 23:56 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 3 unresolved discussions (waiting on @dawnwang22 and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU4MSj1DpuQJVjjx-e:-OAUqF2_-lUqZkoOqjcm:b9pn6np) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/main/kotlin/org/wfanet/measurement/common/rabbitmq/RabbitMqClient.kt#L47)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Depending on something outside of the core Rabbit MQ, especially where there is evidence it's not being maintained, is best avoided.
</blockquote></details>

reactor-rabbitmq is listed as currently supported on the [RabbitMQ Java libraries page](https://www.rabbitmq.com/client-libraries/java-versions). That page also indicates that it's maintained by the RabbitMQ team.

Note that reactor-rabbitmq just wraps the regular Java client library, so it may not need to be released as frequently.


<!-- Sent from Reviewable.io -->

2024-10-31 08:55 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @dawnwang22 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel` line 8 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU3Upz4_wwfxvPAbRQ:-OAWlqZe6qA-cwVTXvD3:bccc02l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can't just assume that RabbitMQ is installed on the local system. Instead you need to add a dependency in MODULE.bazel to download it. We do something similar for cue and the Spanner emulator. You'll want it to download and extract the [Linux binary](https://www.rabbitmq.com/docs/install-generic-unix) and run that from runfiles.
</blockquote></details>

I was not :) I just wanted to get some round of reviews before going into the test. 
Can you please share some code pointer and guideline to be able to run this test using github actions @SanjayVas ?

thank you


<!-- Sent from Reviewable.io -->

2024-10-31 18:08 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 2 unresolved discussions (waiting on @dawnwang22 and @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel` line 8 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU3Upz4_wwfxvPAbRQ:-OAYhDML6pWS_xI5cQkc:b-gc32j6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel#L8)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I was not :) I just wanted to get some round of reviews before going into the test. 
Can you please share some code pointer and guideline to be able to run this test using github actions @SanjayVas ?

thank you
</blockquote></details>

1. Use a repo rule or module extension to download and extract the RabbitMQ binaries. For example, using http_archive with a custom BUILD file to add native_binary targets for the binaries.
    * The `http_archive` repo rule comes from `@bazel_tools//tools/build_defs/repo:http.bzl`
    * `native_binary` comes from `@bazel_skylib//rules:native_binary.bzl`
2. Specify the labels for the binary target(s) you need in the `data` attribute of the dependent test
3. Use `org.wfanet.measurement.common.getRuntimePath` to get the path to the executable in code. Ignore the deprecation warning, as fixing that is blocked on rules_kotlin (see https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1530)

You may want to extract some testing infrastructure to make it easier to run tests that depend on RabbitMQ. `org.wfanet.measurement.gcloud.spanner.testing` has some examples, though those are certainly more complex than you need since that is built to handle creating databases as well as ensuring that we share the emulator process across test methods.


<!-- Sent from Reviewable.io -->

2024-11-19 18:10 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 1 of 15 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel` line 8 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU3Upz4_wwfxvPAbRQ:-OC4bWWhCYvH6oSt3EmP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Use a repo rule or module extension to download and extract the RabbitMQ binaries. For example, using http_archive with a custom BUILD file to add native_binary targets for the binaries.
    * The `http_archive` repo rule comes from `@bazel_tools//tools/build_defs/repo:http.bzl`
    * `native_binary` comes from `@bazel_skylib//rules:native_binary.bzl`
2. Specify the labels for the binary target(s) you need in the `data` attribute of the dependent test
3. Use `org.wfanet.measurement.common.getRuntimePath` to get the path to the executable in code. Ignore the deprecation warning, as fixing that is blocked on rules_kotlin (see https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1530)

You may want to extract some testing infrastructure to make it easier to run tests that depend on RabbitMQ. `org.wfanet.measurement.gcloud.spanner.testing` has some examples, though those are certainly more complex than you need since that is built to handle creating databases as well as ensuring that we share the emulator process across test methods.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-22 18:10 UTC, Marco-Premier reviewed
I have replaced rabbitmq with Google Pub/Sub

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-:-OCK3PQX4-NZW1U7m-77:b-p7lest)* status: 0 of 24 files reviewed, 2 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-11-25 18:53 UTC, SanjayVas requested changes
> Reviewed 6 of 24 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 6 of 24 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 81 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCZeaX5Dfz-iGoU7teL:-OCZeaX5Dfz-iGoU7teM:b-46bxhu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/33831fb14cb7666e38775af16e47140997eb3565/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L81)):*
> ```Kotlin
>             PullRequest.newBuilder().setMaxMessages(1).setSubscription(subscriptionName).build()
> 
>           val pullResponse = runBlocking { subscriberStub.pullCallable()?.call(pullRequest) }
> ```

Use the Cloud Pub/Sub Java client library rather than interacting with the service stub directly. This means using the Subscriber and MessageReceiver classes. See https://cloud.google.com/pubsub/docs/reference/libraries and https://github.com/googleapis/java-pubsub


<!-- Sent from Reviewable.io -->

2024-11-26 17:24 UTC, Marco-Premier reviewed
I have abstracted the code for the GooglePubSubClient to better support ControlPlane API

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-:-OCdV1zp5HtT0pVJBQZ8:b-b4hmu1)* status: 4 of 27 files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 81 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCZeaX5Dfz-iGoU7teL:-OCdV0DN40iq73QSMPTs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/33831fb14cb7666e38775af16e47140997eb3565/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the Cloud Pub/Sub Java client library rather than interacting with the service stub directly. This means using the Subscriber and MessageReceiver classes. See https://cloud.google.com/pubsub/docs/reference/libraries and https://github.com/googleapis/java-pubsub
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 18:16 UTC, SanjayVas requested changes
> Reviewed 10 of 24 files at r7, 4 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 18 of 27 files reviewed, 11 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt` line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdcF319uHxgseqLcY5:-OCdcF319uHxgseqLcY6:b68r8y0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt#L51)):*
> ```Kotlin
>     val publisher = Publisher.newBuilder(topicName).build()
>     val pubsubMessage = PubsubMessage.newBuilder().setData(messageContent).build()
>     publisher.publish(pubsubMessage).get()
> ```

Never call `get` on a future, as that's a blocking operation. Instead make `publishMessage` a suspend function and suspend until the operation completes.



_Code quote:_
```Kotlin
.get()
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt` line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdbdtIBQzWxEUPnjH9:-OCdbdtIBQzWxEUPnjHA:b-hhvnjp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt#L58)):*
> ```Kotlin
>       val topicName = TopicName.of(projectId, topicId)
>       try {
>         topicAdminClient.getTopic(topicName)
> ```

This will call the blocking version of this method. Everything needs to be async coroutine code. This means `topicExists` needs to be a suspend function and use `topicAdminClient.getTopicCallable().futureCall(request)`. You can then await on that ApiFuture using `org.wfanet.measurement.gcloud.common.await`

See https://cloud.google.com/java/docs/reference/google-cloud-pubsub/latest/com.google.cloud.pubsub.v1.TopicAdminClient#com_google_cloud_pubsub_v1_TopicAdminClient_getTopicCallable__
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/BUILD.bazel` line 3 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdd32y2rODDxLCUmNG:-OCdd32y2rODDxLCUmNH:bnapv0h) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/BUILD.bazel#L3)):*
> ```Starlark
> load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")
> 
> package(default_visibility = ["//visibility:public"])
> ```

All testing packages should have `default_testonly = True`
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 52 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCddHL39Ho82b-1Mp76:-OCddHL39Ho82b-1Mp77:bnr4ppp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L52)):*
> ```Kotlin
> class GooglePubSubEmulatorClient : GooglePubSubClient {
> 
>   private val PUBSUB_IMAGE_NAME = "gcr.io/google.com/cloudsdktool/cloud-sdk:317.0.0-emulators"
> ```

Move this to the companion object and mark it `const`.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 62 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdfj8W1oR_rXn2LrwV:-OCdfj8W1oR_rXn2LrwW:b4536rn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L62)):*
> ```Kotlin
> 
>   fun startEmulator() {
>     pubsubEmulator = PubSubEmulatorContainer(DockerImageName.parse(PUBSUB_IMAGE_NAME))
> ```

Separate the management of the emulator from the client implementation. You should be able to have multiple client instances that use the same running emulator instance.

Ultimately you want a JUnit rule for emulator management.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 84 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdej5C5XynWYCF-Ukj:-OCdej5C5XynWYCF-Ukk:b-2fyy54) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L84)):*
> ```Kotlin
>         .build()
>     channelProvider = FixedTransportChannelProvider.create(GrpcTransportChannel.create(channel))
>     credentialsProvider = NoCredentialsProvider.create()
> ```

The CredentialsProvider need not have delayed initialization.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 105 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdfPnm-M_xFudPNLQ6:-OCdfEYj2YnAZzS8voll:beq4q8h) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L105)):*
> ```Kotlin
>   }
> 
>   fun createTopic(projectId: String, topicId: String): TopicName {
> ```

All of these methods which make RPCs must suspend until the operation completes using async calls.
___
*[`src/main/kotlin/org/wfanet/measurement/queue/QueueSubscriber.kt` line 29 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdXT9w8SIqgg6ni2M8:-OCdXT9x7BYGbBa-amYb:b-8ietth) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/queue/QueueSubscriber.kt#L29)):*
> ```Kotlin
> interface QueueSubscriber : AutoCloseable {
> 
>   val blockingContext: CoroutineContext
> ```

I don't think this belongs in the interface.



_Code quote:_
```Kotlin
blockingContext
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/subscriber/Subscriber.kt` line 15 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdcw7q6yq2xAiDdJrK:-OCdcw7q6yq2xAiDdJrL:b-ledr6i) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/subscriber/Subscriber.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.gcloud.pubsub.subscriber
> ```

nit: I don't think you need a subpackage just for this.


<!-- Sent from Reviewable.io -->

2024-11-27 16:48 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 14 of 28 files reviewed, 10 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt` line 51 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdcF319uHxgseqLcY5:-OCi1g3mBraQr1oh8X3P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Never call `get` on a future, as that's a blocking operation. Instead make `publishMessage` a suspend function and suspend until the operation completes.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt` line 58 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdbdtIBQzWxEUPnjH9:-OCi1ck54298__B5geMx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This will call the blocking version of this method. Everything needs to be async coroutine code. This means `topicExists` needs to be a suspend function and use `topicAdminClient.getTopicCallable().futureCall(request)`. You can then await on that ApiFuture using `org.wfanet.measurement.gcloud.common.await`

See https://cloud.google.com/java/docs/reference/google-cloud-pubsub/latest/com.google.cloud.pubsub.v1.TopicAdminClient#com_google_cloud_pubsub_v1_TopicAdminClient_getTopicCallable__
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/BUILD.bazel` line 3 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdd32y2rODDxLCUmNG:-OCi5NKs7jbSO6A24UFK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/BUILD.bazel#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All testing packages should have `default_testonly = True`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 52 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCddHL39Ho82b-1Mp76:-OCi5nFV-f1OM8hc2vDp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this to the companion object and mark it `const`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 62 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdfj8W1oR_rXn2LrwV:-OCiOZnq9o8dUfuMVEG9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Separate the management of the emulator from the client implementation. You should be able to have multiple client instances that use the same running emulator instance.

Ultimately you want a JUnit rule for emulator management.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 84 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdej5C5XynWYCF-Ukj:-OCiPM7IEy3u2M_VBqNt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The CredentialsProvider need not have delayed initialization.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 105 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdfPnm-M_xFudPNLQ6:-OCiWKmvA2BQbAUMJgnW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All of these methods which make RPCs must suspend until the operation completes using async calls.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel` line 7 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OAU77_Z-i6fsAvffF6X:-OCi6Doy6GSwq8Y5_XwR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9e2879aeb6f30d9cca98d49af30e23bf769b04f2/src/test/kotlin/org/wfanet/measurement/common/rabbitmq/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Where does this get read?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/queue/QueueSubscriber.kt` line 29 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCdXT9w8SIqgg6ni2M8:-OCi5v5y7EtDRrs4l7QU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b96ff02271dbdc0293105754bb85467f0ab8badb/src/main/kotlin/org/wfanet/measurement/queue/QueueSubscriber.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this belongs in the interface.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-27 20:27 UTC, SanjayVas requested changes
> Reviewed 4 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 18 of 28 files reviewed, 10 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 50 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjH81--6Cu_vNfOr6A:-OCjH81--6Cu_vNfOr6B:bgci9dv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L50)):*
> ```Kotlin
>  * subscriptions in an emulated environment.
>  */
> class GooglePubSubEmulatorClient(private val host: String, private val port: Int) :
> ```

Given the similarities between this and DefaultGooglePubSubClient, it seems to me that it would be better to have an abstract base class for both that has abstract methods/properties for the differences. As far as I can tell, this is just building the clients. Perhaps then you want something like

```kotlin
private val topicAdminClient by lazy {
  buildTopicAdminClient()
}

protected abstract fun buildTopicAdminClient(): TopicAdminClient
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 53 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjGAkC185lmgSX9XQZ:-OCjGAkC185lmgSX9XQ_:bmb9vi0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L53)):*
> ```Kotlin
>   GooglePubSubClient, AutoCloseable {
> 
>   private lateinit var channel: ManagedChannel
> ```

If these are all initialized as part of the object initialization, then they don't need to be `lateinit`. In fact, I think you probably can drop the `init` block and corresponding methods and just combine initialization with property definition.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt` line 34 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjIIag6rWFf5xkpv-u:-OCjIIag6rWFf5xkpv-v:b-e1ikpf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt#L34)):*
> ```Kotlin
>     get() = pubsubEmulator.getMappedPort(8085)
> 
>   fun startEmulator() {
> ```

Start and stop should be private.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt` line 59 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjIRKS46ktufrRrTDg:-OCjIRKS46ktufrRrTDh:buc3kym) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt#L59)):*
> ```Kotlin
> 
>   companion object {
>     const val PUBSUB_IMAGE_NAME = "gcr.io/google.com/cloudsdktool/cloud-sdk:317.0.0-emulators"
> ```

private
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt` line 51 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjEVtVDvfTWB-IuHOA:-OCjEVtVDvfTWB-IuHOB:byybjk8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt#L51)):*
> ```Kotlin
>   override suspend fun publishMessage(projectId: String, topicId: String, message: Message) {
>     val topicName = TopicName.of(projectId, topicId)
>     val publisher = Publisher.newBuilder(topicName).build()
> ```

The Publisher shouldn't be recreated for each message and should be reused. Ultimately, you'll want a QueuePublisher interface to live alongside QueueSubscriber. For this client class, I think you just want a `buildPublisher` similar to `buildSubscriber`.


<!-- Sent from Reviewable.io -->

2024-11-29 09:48 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 15 of 31 files reviewed, 10 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt` line 51 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjEVtVDvfTWB-IuHOA:-OCrJBsT3JLFuhFXiOOm:bkq88rq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/DefaultGooglePubSubClient.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Publisher shouldn't be recreated for each message and should be reused. Ultimately, you'll want a QueuePublisher interface to live alongside QueueSubscriber. For this client class, I think you just want a `buildPublisher` similar to `buildSubscriber`.
</blockquote></details>

good point, Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 50 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjH81--6Cu_vNfOr6A:-OCrJSos6yYRJ9QUiS9F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Given the similarities between this and DefaultGooglePubSubClient, it seems to me that it would be better to have an abstract base class for both that has abstract methods/properties for the differences. As far as I can tell, this is just building the clients. Perhaps then you want something like

```kotlin
private val topicAdminClient by lazy {
  buildTopicAdminClient()
}

protected abstract fun buildTopicAdminClient(): TopicAdminClient
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt` line 53 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjGAkC185lmgSX9XQZ:-OClZX_EEbFw_zDZ92Ue:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorClient.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If these are all initialized as part of the object initialization, then they don't need to be `lateinit`. In fact, I think you probably can drop the `init` block and corresponding methods and just combine initialization with property definition.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt` line 34 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjIIag6rWFf5xkpv-u:-OClWGyw10HdOujnyPt5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Start and stop should be private.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt` line 59 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OCjIRKS46ktufrRrTDg:-OClWCI82h7i5nTDOpdi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5fcdfd64e4e955f2735b9a7bf6e575ec3f221461/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/testing/GooglePubSubEmulatorProvider.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-02 14:32 UTC, stevenwarejones requested changes
> Reviewed 16 of 24 files at r7, 2 of 11 files at r8, 3 of 11 files at r9, 12 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 13 unresolved discussions (waiting on @dawnwang22, @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/queue/BUILD.bazel` line 8 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD6ljDy3LZCAVxVylqX:-OD6ljDy3LZCAVxVylqY:b-kerfy9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9dde736a795b633978abb965e17a94e261d8ab97/src/main/proto/wfa/measurement/queue/BUILD.bazel#L8)):*
> ```Starlark
> )
> 
> package(default_visibility = ["//visibility:public"])
> ```

these should be under `queue/testing` and be `test_only`
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 118 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD6mCsK2hI8rrTu1ggx:-OD6mCsK2hI8rrTu1ggy:b-fv5nu2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9dde736a795b633978abb965e17a94e261d8ab97/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L118)):*
> ```Kotlin
>         .setTopic(topicName.toString())
>         .setPushConfig(PushConfig.getDefaultInstance())
>         .setAckDeadlineSeconds(10)
> ```

can you make this a constant?
___
*[`src/main/proto/wfa/measurement/queue/test_work.proto` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD6laWD-ItuqTKEoguf:-OD6laWD-ItuqTKEogug:b-oxtny4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9dde736a795b633978abb965e17a94e261d8ab97/src/main/proto/wfa/measurement/queue/test_work.proto#L1)):*
> ```proto
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

this should be under `queue/testing` imo


<!-- Sent from Reviewable.io -->

2024-12-03 12:01 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 18 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 118 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD6mCsK2hI8rrTu1ggx:-OD6rJk038oWdRWSjaGM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9dde736a795b633978abb965e17a94e261d8ab97/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L118)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make this a constant?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 57 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD7vuKwDZXGufmh_VWR:-ODAfvnI5IyFTa7ndoU0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fix references for disambiguation.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 131 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD7wOE01Jd2QiI1S12w:-ODAh1ywAx8puIqDfCNB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than casting here (where I'm not even sure if this behavior is documented), you can instead have the property be of type Lazy rather than using the `lazy` property delegate. i.e.

```kotlin
private val topicAdminClient: Lazy<TopicAdminClient> = lazy { buildTopicAdminClient() }
```

And then you can use `topicAdminClient.isInitialized()` and `topicAdminClient.value`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 140 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD80SWR0ZqvY9ve0fHs:-ODAiXt-1fXQTvRubb0I:b-9czcne) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L140)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This appears to be the [documented default](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/create). Can you just avoid setting it and add the constant (or a parameter) if we want to support changing it?
</blockquote></details>

I have simply removed it as it's used only for local  testing ( subscription on google pubsub will be created using terraform. 
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Publisher.kt` line 49 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD83Z_J5WPg80JE5S0r:-ODBNuamCr9KXlkYXSOf:bpmorfz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Publisher.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does the service implementation not throw its own exception for this that we can wrap and bubble up? It seems unnecessary to make a separate call for this every time we're publishing a message.

Note that this should have some error handling to not expose exceptions specific to Google Pub/Sub to users of the QueuePublisher interface.
</blockquote></details>

you are right, also created ad-hoc exceptions.
___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt` line 28 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD82Q8C8hE-ipthN0Ly:-ODBGGVS7NXi4jmk6hv3:b-ow0rtw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: ideally we'd have an abstract test class that uses the QueueSubscriber and QueuePublisher interfaces, where the specific implementation would override methods for subscribing and creating subscriptions. The subscriber test would inherently rely on the QueuePublisher implementation.
</blockquote></details>

I think I prefer have tests in two separate classes and don't wrap tests in the abstract class as different queue provider will most likely need different tests (eg. rabbitmq) and so the abstract class would probably be limited to Google implementation
___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt` line 32 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD81SJI47qoJIK2RmSp:-ODAvr2W1nbTgnhDoxXS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These can be constants defined in the companion object. Note that not every expression needs to be a const expression to still be considered a constant and use CONST_CASE (e.g. immutable lists can be constants even though the property cannot be defined with the `const` keyword)
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt` line 94 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD81zpFBCVarAeNM21U:-ODBNqZT48pjhHokpNYa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt#L94)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use assertFailsWith from kotlin.test. Though note that if we care about the exception behavior, this should be using a documented specific exception type. Assertions should not be made on the whole message, and should only be made on parts of the message at all if absolutely necessary for disambiguation of error types (which in an API we control, would be a sign that it should be a more granular exception type instead).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 43 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD8743hAJn4CZrQwjUz:-ODAuT5x0B-BGcY_mtJl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We shouldn't need a `@BlockingExecutor` context since we have a fully asynchronous GooglePubsubClient. Therefore this shouldn't be called `blockingContext`. Instead, this is just the coroutine context used for producing the channel.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD84VFq2ePK1 [...]

2024-12-03 15:42 UTC, stevenwarejones approved these changes
> Reviewed 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 18 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-03 19:24 UTC, SanjayVas requested changes
> Reviewed 1 of 12 files at r10, 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 18 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 57 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD7vuKwDZXGufmh_VWR:-ODCnZLC4yvPfoyVF02z:b-bkpu4m) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L57)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed other cases, such as the `@return` for this method and the KDoc for `buildPublisher`.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt` line 140 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD80SWR0ZqvY9ve0fHs:-ODCnpcY8izx7UBzPDEY:b2xuswp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/GooglePubSubClient.kt#L140)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I have simply removed it as it's used only for local  testing ( subscription on google pubsub will be created using terraform.
</blockquote></details>

If that's the case, shouldn't the `createSubscription` and `deleteSubscription` methods be a part of the test-only `GooglePubSubEmulatorClient` rather than `GooglePubSubClient`?

We don't need to offer functionality in GooglePubSubClient that will only be used in tests.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Publisher.kt` line 49 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD83Z_J5WPg80JE5S0r:-ODCojYQ0-nNMdIXpYS_:bhq7iub) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Publisher.kt#L49)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

you are right, also created ad-hoc exceptions.
</blockquote></details>

This means you can also drop `topicExists` from `GooglePubSubClient`, right?
___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt` line 28 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD82Q8C8hE-ipthN0Ly:-ODCxlok7UUz3WILxwG5:b-urmplc) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt#L28)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I think I prefer have tests in two separate classes and don't wrap tests in the abstract class as different queue provider will most likely need different tests (eg. rabbitmq) and so the abstract class would probably be limited to Google implementation
</blockquote></details>

The abstract class would have all the tests that apply to every impl, as all impls should have common behavior. The concrete test class can still add additional impl-specific test methods.
___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt` line 104 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD81NVsEVStyX9-VOLP:-ODCy4ZdBRu2iG7Nk3_-:b-i1d33q) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use Kotlin DSL builder
</blockquote></details>

This isn't using the Kotlin DSL builder for protobufs, but rather just the `apply` Kotlin scope function. When you're using the DSL builder, you will never interact with protobuf Builder objects directly (i.e. never call `newBuilder()`)

```kotlin
return testWork {
  userName = message
  userAge = "25"
  userCountry = "US"
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 41 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCp_0C8e_oVQAwqGvs:-ODCp_0C8e_oVQAwqGvt:bjxr89v) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L41)):*
> ```Kotlin
>  * @param projectId The Google Cloud project ID.
>  * @param googlePubSubClient The client interface for interacting with the Google Pub/Sub service.
>  * @param context The coroutine context used for producing the channel, defaulting to [Dispatchers.IO].
> ```

nit: you don't need to duplicate this information from the method signature



_Code quote:_
```Kotlin
, defaulting to [Dispatchers.IO]
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 44 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCpPxMDZodnoKVcUhz:-ODCpPxMDZodnoKVcUi-:bt4y3tz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L44)):*
> ```Kotlin
>  */
> class Subscriber(
>   val projectId: String,
> ```

Can these be private?
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 46 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCwijX6WC9k0RnzyOo:-ODCwijX6WC9k0RnzyOp:basycsd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L46)):*
> ```Kotlin
>   val projectId: String,
>   val googlePubSubClient: GooglePubSubClient = DefaultGooglePubSubClient(),
>   val context: CoroutineContext = Dispatchers.IO,
> ```

This should default to Dispatchers.Default if we don't need to handle blocking calls.



_Suggestion:_
```Kotlin
Dispatchers.Default
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 51 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCpjfu7W9lotiGm4Kb:-ODCpjfu7W9lotiGm4Kc:bct34eb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L51)):*
> ```Kotlin
>   private val scope = CoroutineScope(context)
> 
>   @kotlinx.coroutines.ExperimentalCoroutinesApi
> ```

1. Use OptIn to indicate you're opting in to using this API. This is instead marking this method as *part* of that API.
2. Document what you're opting in for.



_Suggestion:_
```Kotlin
@OptIn(ExperimentalCoroutinesApi::class) // For `produce`.
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 62 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCqiGX8VOPeQ8ZLdtM:-ODCqiGX8VOPeQ8ZLdtN:bl6bzm1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L62)):*
> ```Kotlin
>         ackExtensionPeriod = Duration.ofHours(6),
>       ) { message, consumer ->
>         launch {
> ```

Why do you need to use `launch` here?
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of [...]

2024-12-04 18:00 UTC, SanjayVas requested changes
> Reviewed 14 of 14 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 3 unresolved discussions (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt` line 104 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-OD81NVsEVStyX9-VOLP:-ODHl_b-73Nn2W0uCplL:b-3he61s) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/96157d83c066fbcfc99f7910ab87d89684896c2c/src/test/kotlin/org/wfanet/measurement/gcloud/pubsub/PublisherTest.kt#L104)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

oh I see, beyond the codding style is there any advantage not using the builder?
</blockquote></details>

It constrains mutability further as you don't have a mutable builder object that can be passed around. You only ever get fully-built immutable message instances.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCsD6f3GUKXy9vIiYa:-ODHiejCDa2wm_QNDEXL:b6roufx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L71)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed the handling the result part. trySend returns a ChannelResult which you need to check. Also note the behavior - trySend does not block and instead returns a failure if the receiver isn't ready and waiting to receive the message.

Since you opted to have the caller handle acking/nacking, then you may instead want to use `trySendBlocking` and go back to annotating the CoroutineContext with`@BlockingExecutor` and defaulting it to `Dispatchers.IO`. Otherwise you may end up "consuming" all the messages from the pub/sub subscriber but not doing anything with them.

In BlockingQueue terms, `trySend` is like `offer` and `send`/`trySendBlocking` is like `put`. The difference between `send` and `trySendBlocking` is suspending vs. blocking.
___
*[`src/test/kotlin/org/wfanet/measurement/queue/AbstractQueueTest.kt` line 125 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODHkqIQ3n3LBE6GGOiV:-ODHkqIQ3n3LBE6GGOiW:brusn5c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3ea380135921cef58b3b5126d99988359a625da3/src/test/kotlin/org/wfanet/measurement/queue/AbstractQueueTest.kt#L125)):*
> ```Kotlin
>   companion object {
> 
>     const val PROJECT_ID = "test-project"
> ```

Project ID is a concept specific to Google Pub/Sub, so this should be in that test class instead.
___
*[`src/main/kotlin/org/wfanet/measurement/queue/QueuePublisher.kt` line 29 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODHjEJdAfJvbB85bEEn:-ODHjEJdAfJvbB85bEEo:biq8dzr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3ea380135921cef58b3b5126d99988359a625da3/src/main/kotlin/org/wfanet/measurement/queue/QueuePublisher.kt#L29)):*
> ```Kotlin
>    * @param topicId The ID of the topic to publish the message to.
>    * @param message The message to be published, where [T] is a type that extends [Message].
>    * @throws [TopicNotFoundException] If the provided Topic ID does not exist.
> ```

nit: you don't need the reference syntax (brackets) here since this will always be a type



_Suggestion:_
```Kotlin
TopicNotFoundException
```


<!-- Sent from Reviewable.io -->

2024-12-04 19:26 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 1 unresolved discussion (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCsD6f3GUKXy9vIiYa:-ODI7QexCiZB9hjaNo4h:b-ptfni5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L71)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

thanks for that. What I was thinking is that the subscriber is built to basically handle one message at the time so there should not risk of receiving a new message till the previous one was either ack or nack, meaning `trySend` won't find the queue filled (Randevouz).

I didn't used `send`/`trySendBlocking` for that reason with this latest refactor.
In the worst case, if a message for any reason gets delivered to the subscriber but trySend fails, the message will be re-delivered by pubsub because neither ack / nack was sent
</blockquote></details>

You still need to handle the closed result even if you're ignoring the failed result.


<!-- Sent from Reviewable.io -->

2024-12-05 11:26 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @dawnwang22, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCsD6f3GUKXy9vIiYa:-ODLZOZj3Zz7nXn0DJa5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You still need to handle the closed result even if you're ignoring the failed result.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-06 00:33 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: all files reviewed, 1 unresolved discussion (waiting on @dawnwang22, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCsD6f3GUKXy9vIiYa:-ODOJJYd6zEZQqhtsjxR:b-26qah9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L71)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Considering this again I think you really do want this to use trySendBlocking. This is most likely getting messages from Pub/Sub potentially in a separate thread than the message receiver. This means that any time you're getting messages faster than they can be processed (which is quite likely e.g. if they come in batches), you'll be forcing redelivery.


<!-- Sent from Reviewable.io -->

2024-12-06 08:33 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: 27 of 34 files reviewed, 1 unresolved discussion (waiting on @dawnwang22, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCsD6f3GUKXy9vIiYa:-ODQ4tNqA2dlLd1xOPTr:b-14haas) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Considering this again I think you really do want this to use trySendBlocking. This is most likely getting messages from Pub/Sub potentially in a separate thread than the message receiver. This means that any time you're getting messages faster than they can be processed (which is quite likely e.g. if they come in batches), you'll be forcing redelivery.
</blockquote></details>

Done. If there are just other nit could you please approve the PR? I really want to get things going and here we are going back and forth which I believe is becoming counterproductive.
thanks


<!-- Sent from Reviewable.io -->

2024-12-06 23:08 UTC, SanjayVas approved these changes
> Reviewed 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dawnwang22 and @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt` line 71 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286#-ODCsD6f3GUKXy9vIiYa:-ODTDkqlC8ftQWTWIS_1:b-l4ea4w) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ea14b7cad23bb8f1dc68216737edae1c6f8ff907/src/main/kotlin/org/wfanet/measurement/gcloud/pubsub/Subscriber.kt#L71)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done. If there are just other nit could you please approve the PR? I really want to get things going and here we are going back and forth which I believe is becoming counterproductive.
thanks
</blockquote></details>

Not even any nits remaining, just approved :)


<!-- Sent from Reviewable.io -->

2024-12-09 01:40 UTC, Marco-Premier reviewed
> Reviewed 14 of 24 files at r7, 1 of 11 files at r9, 1 of 12 files at r10, 1 of 6 files at r11, 1 of 10 files at r12, 3 of 14 files at r13, 4 of 7 files at r16, 9 of 9 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/286)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dawnwang22 and @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-12-09 01:50 UTC, merged