fix!: Verify audience claim matches client ID for OpenID provider
world-federation-of-advertisers/common-jvm pull request #290
Opened 2024-12-17 22:24 UTC by SanjayVas

This addresses a bug in #288 

The client ID is generated by the OpenID provider on registration, so the OpenID provider configuration needs to include the client ID.

2024-12-17 22:24 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/290)
<!-- Reviewable:end -->

2024-12-18 15:35 UTC, stevenwarejones requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/290)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/290#-OEPPGfMEuVBBs98hYc8:-OEPPGfMEuVBBs98hYc9:b-lgii2w) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/966a317afcfd2fad5084d5b69121ead5f5782f1b/src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt#L78)):*
> ```Kotlin
> 
>   @Test
>   fun `verifyAndDecodeBearerToken throws UNAUTHENTICATED when audience does not match`() {
> ```

why is this test not needed?


<!-- Sent from Reviewable.io -->

2024-12-18 18:13 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/290)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/290#-OEPPGfMEuVBBs98hYc8:-OEPmGHh1kkCRp75_MSF:b6j2m0o) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/966a317afcfd2fad5084d5b69121ead5f5782f1b/src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is this test not needed?
</blockquote></details>

Done. Figured out a different way to test it.


<!-- Sent from Reviewable.io -->

2024-12-19 14:25 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/290)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-19 18:13 UTC, merged