Make Store write/get methods open for AeadStore
world-federation-of-advertisers/common-jvm pull request #44
Opened 2021-10-05 14:46 UTC by corbantek

- Inorder to implement AeadStore, the write and get methods need to be overridden so that the blob content can be encrypted before write and decrypted before returning from super

2021-10-05 15:33 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44#-MlG4Q_N-JrSlKIATnco:-MlG4Q_N-JrSlKIATncp:b2azhjs) (no related file):*
In reference to https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/25/commits/f38944ee84a025b201f25a90e5b1df0ca2db6599#diff-9ef48ca35d57a4d8b0bb280b0f92579906dbad5f17e9b72fd8d4d73c1bf43a7b

---


<!-- Sent from Reviewable.io -->

2021-10-05 17:42 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44#-MlGXqGG3NcK7Ah3TTzZ:-MlGXqGH0F1IDhEbPY_P:b9wsmuf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/729a8fab513a2a6edebc8eb38355b90150f46e7a/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L58)):*
> ```
> open 
> ```
Does this one need to be open? It just calls the other `write` overload.


<!-- Sent from Reviewable.io -->

2021-10-05 18:27 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44#-MlGXqGG3NcK7Ah3TTzZ:-MlGgV2YEcC6_4yesm6z:bt40fmx) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/729a8fab513a2a6edebc8eb38355b90150f46e7a/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> open 
> ```
Does this one need to be open? It just calls the other `write` overload.
</blockquote></details>

I didn't want to be dependent on the lower implementation by only overriding a single write, what if later the Store impl changes and doesn't call the other one and then it wont perform the encrypt/decrypt properly


<!-- Sent from Reviewable.io -->

2021-10-05 18:38 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44#-MlGXqGG3NcK7Ah3TTzZ:-MlGjWlz-GKXMKvaGueU:b-9fumdt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/729a8fab513a2a6edebc8eb38355b90150f46e7a/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L58)):*
> what if later the Store impl changes and doesn't call the other one and then it wont perform the encrypt/decrypt properly

This is part of the `Store` contract. Feel free to list explicitly in the KDoc for this `write` overload that it calls the other one.


<!-- Sent from Reviewable.io -->

2021-10-05 23:09 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @duliomatos1, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-10-06 02:14 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44#-MlGXqGG3NcK7Ah3TTzZ:-MlIKYxo6Gm__tGQdGFA:bweatre) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/729a8fab513a2a6edebc8eb38355b90150f46e7a/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> what if later the Store impl changes and doesn't call the other one and then it wont perform the encrypt/decrypt properly

This is part of the `Store` contract. Feel free to list explicitly in the KDoc for this `write` overload that it calls the other one.
</blockquote></details>

Okay sure, and I'll remove the open keyword from this `write`


<!-- Sent from Reviewable.io -->

2021-10-06 06:07 UTC, corbantek commented
Abandoning in favor of https://github.com/world-federation-of-advertisers/common-jvm/pull/45

2021-10-06 06:07 UTC, closed without merging