Add base64 encoding conversions for ByteString and Long.
world-federation-of-advertisers/common-jvm pull request #74
Opened 2021-12-13 23:48 UTC by SanjayVas

This technically makes a "breaking" change by swapping the return type of String.base64UrlEncode, but all known calls should be unaffected.

2021-12-14 00:16 UTC, efoxepstein requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/Base64.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74#-MqqH5zS9caFiXl4Pe0I:-MqqH5zS9caFiXl4Pe0J:bg7tt4v) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2bae1b479f1abd00cdca46ebe40455045db2ecc7/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L35)):*
> ```Kotlin
> 
> fun Long.base64UrlEncode(): String {
>   val buffer = ByteBuffer.allocate(8).order(ByteOrder.BIG_ENDIAN).putLong(this)
> ```

Can this use Long.toByteString?
___
*[src/main/kotlin/org/wfanet/measurement/common/Base64.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74#-MqqHqPm-b-NawEbw3oW:-MqqHqPm-b-NawEbw3oX:b5kabjv) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2bae1b479f1abd00cdca46ebe40455045db2ecc7/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L45)):*
> ```Kotlin
> 
> private fun ByteBuffer.encode(encoder: Base64.Encoder): String {
>   return String(encoder.encode(this).array(), Charsets.ISO_8859_1)
> ```

OOC why this charset?


<!-- Sent from Reviewable.io -->

2021-12-14 16:44 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @kungfucraig, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/Base64.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74#-MqqH5zS9caFiXl4Pe0I:-MqtnhB70apP6yf9U79Q:b6rpl5b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2bae1b479f1abd00cdca46ebe40455045db2ecc7/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can this use Long.toByteString?
</blockquote></details>

There's no need to copy to a ByteString. I extracted `Long.toReadOnlyByteBuffer()` instead to share the logic.
___
*[src/main/kotlin/org/wfanet/measurement/common/Base64.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74#-MqqHqPm-b-NawEbw3oW:-MqtmbIaAGNUwzyHxmwc:b-ina81d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2bae1b479f1abd00cdca46ebe40455045db2ecc7/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC why this charset?
</blockquote></details>

It's what's documented in Base64.Encoder for its String conversions.


<!-- Sent from Reviewable.io -->

2021-12-14 17:30 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)



<!-- Sent from Reviewable.io -->

2021-12-14 18:22 UTC, kungfucraig requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/Base64.kt, line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74#-MquAWGq0n3s1O5lKMqe:-MquAWGq0n3s1O5lKMqf:b-227cdd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3e004a7ed12b636de990791c23f806d96bdb8306/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.common
> ```

I don't see tests for this file.


<!-- Sent from Reviewable.io -->

2021-12-14 18:35 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-12-14 20:04 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)

___
*[src/main/kotlin/org/wfanet/measurement/common/Base64.kt, line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74#-MquAWGq0n3s1O5lKMqe:-MquXuGFER6wTMosn3uu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3e004a7ed12b636de990791c23f806d96bdb8306/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L15)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't see tests for this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-14 20:44 UTC, efoxepstein approved these changes
> Reviewed 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2021-12-15 17:41 UTC, kungfucraig approved these changes
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-12-15 17:56 UTC, merged