randomize storage keys for abstract storage client tests
world-federation-of-advertisers/common-jvm pull request #86
Opened 2022-01-25 17:29 UTC by stevenwarejones

Some of these tests already using randomized keys. This extends this to the rest of the tests for build environments that run these tests multiple times in parallel.

2022-01-25 18:58 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86#-MuHaAYv7PonVYWsF1rk:-MuHaAYv7PonVYWsF1rl:b-asqgui) (no related file):*
> This extends this to the rest of the tests for build environments that run these tests multiple times in parallel.

Can you clarify why this would be needed? Our tests should already be isolated such that they can be run in parallel. Is there some implementation of this that is e.g. sharing the underlying storage across runs?

---


<!-- Sent from Reviewable.io -->

2022-01-25 22:07 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86#-MuHaAYv7PonVYWsF1rk:-MuIGDV9CFLm_e4R84L3:b-ovael3) (no related file):*
My basic point is that the implementing test class should be guaranteeing isolation. We shouldn't need to randomize blob names for this purpose.

> The filesystem test already in the repo can't be run 2x in parallel either.

It can't? It uses the TemporaryDirectory rule, so it should be creating a separate temp dir for each run.

---


<!-- Sent from Reviewable.io -->

2022-01-27 01:13 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86#-MuHaAYv7PonVYWsF1rk:-MuO4pYuES6-qkzVFuz8:b-4xrds1) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My basic point is that the implementing test class should be guaranteeing isolation. We shouldn't need to randomize blob names for this purpose.

> The filesystem test already in the repo can't be run 2x in parallel either.

It can't? It uses the TemporaryDirectory rule, so it should be creating a separate temp dir for each run.
</blockquote></details>

You're 100% right. Not sure what I was thinking... too much multi-tasking.... anyways, I do have a use case with storage that fails with the current tests. If you think its bad practice to encourage it, we can leave it as is, but I'd prefer to merge this.

---


<!-- Sent from Reviewable.io -->

2022-01-27 19:20 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/86#-MuHaAYv7PonVYWsF1rk:-MuRySsJ65w38HPmsQOD:b-b0v95o) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

You're 100% right. Not sure what I was thinking... too much multi-tasking.... anyways, I do have a use case with storage that fails with the current tests. If you think its bad practice to encourage it, we can leave it as is, but I'd prefer to merge this.
</blockquote></details>

I think the priority would be figuring out how to fix that test, as the test setup itself should ensure isolation. That is to say that this test should be free to use the same keys across calls with the assumption that test runs cannot conflict.

---


<!-- Sent from Reviewable.io -->

2022-01-27 22:35 UTC, closed without merging